"use strict";
(function(root){const c=root.ImoancyJubilacionCore;let passed=0,failures=[];function test(n,f){try{f();passed++}catch(e){failures.push(n+": "+e.message)}}function ok(x,m){if(!x)throw Error(m||"assertion failed")}function eq(a,b){if(a!==b)throw Error(a+" !== "+b)}
function base(x){return Object.assign({birthDate:"1962-06-15",asOfDate:"2026-06-15",contributedMonthsAsOfDate:450,continueContributing:false,specificCarenceMet:true},x||{})}
for(const year of [2013,2019,2020,2022,2023,2026,2027,2035])test("monotonía porcentaje "+year,()=>{let prior=-1;for(let m=180;m<=500;m++){let r=c.calculatePensionPercentage({eventYear:year,contributedMonths:m});ok(r.rate>=prior&&r.rate<=1);prior=r.rate}});
for(const year of [2026,2027])test("identidades pensión "+year,()=>{for(let m=180;m<=500;m+=7){for(const reduction of [0,.005,.0281,.055,.13,.21,.30]){let r=c.calculateRetirementPension({baseRegulatory:1234.56789,contributedMonths:m,eventYear:year,reductionRate:reduction});eq(r.status,c.STATUS.OK);ok(r.monthlyGross<=r.monthlyGrossBeforeReduction);ok(r.monthlyDifference>=0);ok(Math.abs(r.monthlyGross-(r.monthlyGrossBeforeReduction*(1-reduction)))<1e-10);ok(Math.abs(r.annualGross-r.monthlyGross*14)<1e-10)}}});
test("filas voluntarias no cruzadas",()=>{for(let e=1;e<=24;e++){let r=c.calculateEarlyRetirementScenario(Object.assign(base({contributedMonthsAsOfDate:534}),{mode:"VOLUNTARY",monthsEarly:e}));eq(r.reductionRate,c.NORMATIVA.voluntaryEarly.table.find(x=>x.monthsEarly===e).rates[3])}});
test("filas involuntarias no cruzadas",()=>{for(let e=1;e<=48;e++){let r=c.calculateEarlyRetirementScenario(Object.assign(base({contributedMonthsAsOfDate:534}),{mode:"INVOLUNTARY",monthsEarly:e}));eq(r.reductionRate,c.NORMATIVA.involuntaryEarly.table.find(x=>x.monthsEarly===e).rates[3])}});
test("columnas exactas",()=>{for(const mode of ["VOLUNTARY","INVOLUNTARY"]){let table=mode==="VOLUNTARY"?c.NORMATIVA.voluntaryEarly.table:c.NORMATIVA.involuntaryEarly.table;for(const e of [1,6,12,24])for(const pair of [[461,0],[462,1],[497,1],[498,2],[533,2],[534,3]]){let months=Math.max(pair[0],mode==="VOLUNTARY"?420:396);let r=c.calculateEarlyRetirementScenario(Object.assign(base({contributedMonthsAsOfDate:months}),{mode:mode,monthsEarly:e}));eq(r.reductionRate,table.find(x=>x.monthsEarly===e).rates[pair[1]])}}});
test("deep frozen input",()=>{let x=base({creditedAdditionalMonths:1});Object.freeze(x);let a=JSON.stringify(c.calculateRetirement(x)),b=JSON.stringify(c.calculateRetirement(x));eq(a,b)});
test("orden de llamadas irrelevante",()=>{let x=base();let a=JSON.stringify(c.calculateOrdinaryRetirement(x));c.calculatePensionPercentage({eventYear:2026,contributedMonths:300});c.calculateBaseRegulatory({mode:"CONTRIBUTION_BASE_HISTORY",monthlyBases:[1]});eq(JSON.stringify(c.calculateOrdinaryRetirement(x)),a)});
test("ningún OK contiene no finitos",()=>{for(let m=180;m<=500;m+=5){let r=c.calculateRetirementPension({baseRegulatory:999.99,contributedMonths:m,eventYear:2026,reductionRate:.13});for(const k of Object.keys(r))if(typeof r[k]==="number")ok(Number.isFinite(r[k]),k)}});
test("sin carencia no abre vía alternativa",()=>{for(const m of [0,1,12,179]){let x=base({contributedMonthsAsOfDate:m});eq(c.calculateEarlyRetirementScenario(Object.assign(x,{mode:"VOLUNTARY",monthsEarly:12})).status,c.STATUS.NOT_ELIGIBLE);eq(c.calculateEarlyRetirementScenario(Object.assign(x,{mode:"INVOLUNTARY",monthsEarly:12})).status,c.STATUS.NOT_ELIGIBLE)}});
root.ImoancyJubilacionPropertiesResult={passed,failed:failures.length,failures};}(typeof globalThis!=="undefined"?globalThis:this));
