"use strict";
(function(){
 const frame=document.getElementById("app"),output=document.getElementById("test-output");let passed=0,failures=[];
 function test(name,fn){try{fn();passed+=1;}catch(e){failures.push(name+": "+e.message);}}
 function ok(value,message){if(!value)throw Error(message||"assertion failed");}
 function eq(a,b){if(a!==b)throw Error(String(a)+" !== "+String(b));}
 function text(doc,id){return doc.getElementById(id).textContent.replace(/\u00a0/g," ");}
 function radio(doc,name,value){const x=doc.querySelector('input[name="'+name+'"][value="'+value+'"]');x.checked=true;x.dispatchEvent(new Event("change",{bubbles:true}));}
 function value(doc,id,v){const x=doc.getElementById(id);x.value=v;x.dispatchEvent(new Event("input",{bubbles:true}));}
 function fillMain(doc,overrides){const x=Object.assign({birth:"1961-06-15",asOf:"2026-06-15",years:"38",months:"3",continued:"no",specific:"yes"},overrides||{});radio(doc,"generalRegime","yes");value(doc,"birthDate",x.birth);value(doc,"asOfDate",x.asOf);value(doc,"contributionYears",x.years);value(doc,"contributionMonths",x.months);radio(doc,"continueContributing",x.continued);radio(doc,"specificCarence",x.specific);doc.getElementById("retirement-form").dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));}
 frame.addEventListener("load",function(){const w=frame.contentWindow,d=w.document;w.gtag=function(){w.__events=(w.__events||[]).concat([Array.from(arguments)]);};
  test("estado inicial progresivo",function(){ok(d.getElementById("results").hidden);ok(!d.getElementById("asOfDate").value.match(/^$/));eq(d.querySelectorAll('#retirement-form input[type="number"]').length,2);});
  test("controles con nombre accesible",function(){d.querySelectorAll("input").forEach(function(x){ok(x.closest("label")||d.querySelector('label[for="'+x.id+'"]'),"sin label: "+(x.id||x.name));});d.querySelectorAll("button").forEach(function(x){ok(x.textContent.trim().length>0);});ok(d.querySelector("h1")&&d.querySelectorAll("h2").length>0);});
  test("ejemplo editorial anticipado procede del motor",function(){const c=w.ImoancyJubilacionCore,input={birthDate:"1961-06-15",asOfDate:"2024-06-15",contributedMonthsAsOfDate:438,continueContributing:true,specificCarenceMet:true},expected=[[24,"−21,00 %","1.580,00 €"],[18,"−8,80 %","1.824,00 €"],[12,"−5,50 %","1.890,00 €"],[6,"−4,00 %","1.920,00 €"]],visible=text(d,"ejemplo-anticipacion");expected.forEach(function(x){const early=c.calculateEarlyRetirementScenario(Object.assign({},input,{mode:"VOLUNTARY",monthsEarly:x[0]})),p=c.calculateRetirementPension({baseRegulatory:2000,contributedMonths:early.contributedMonthsAtProposedDate,eventYear:Number(early.proposedRetirementDate.slice(0,4)),reductionRate:early.reductionRate});eq("−"+(early.reductionRate*100).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" %",x[1]);eq(p.monthlyGross,x[0]===24?1580:x[0]===18?1824:x[0]===12?1890:1920);ok(visible.includes(x[1])&&visible.includes(x[2]));});});
  test("ejemplo editorial demorado procede del motor",function(){const c=w.ImoancyJubilacionCore,r=c.calculateDeferredPercentageBonus({ordinaryRetirementDate:"2026-06-15",deferredRetirementDate:"2027-06-15",effectiveContributionMonthsDuringDeferral:12,ordinaryCarenceMet:true,baseRegulatory:2000,ordinaryPercentageRate:1,pensionMaximumAnnual:40000});eq(r.additionalPercentageRate,.04);eq(r.pension.monthlyGrossAfterBonus,2080);ok(text(d,"ejemplo-demora").includes("+4,00 %"));ok(text(d,"ejemplo-demora").includes("2.080,00 €"));});
  test("validación junto al campo",function(){d.getElementById("retirement-form").dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));ok(text(d,"generalRegime-error").length>0);eq(d.querySelector('input[name="generalRegime"]').getAttribute("aria-invalid"),"true");});
  fillMain(d);
  test("resultado ordinario 2026",function(){ok(!d.getElementById("results").hidden);ok(text(d,"main-results").includes("65 años"));ok(text(d,"main-results").includes("15/06/2026"));});
  test("voluntaria y comparador",function(){ok(text(d,"main-results").includes("Podrías cumplir"));ok(d.querySelectorAll("#early-comparison .escenario").length>=4);ok(text(d,"early-comparison").includes("24 meses antes"));});
  test("comparación central",function(){eq(d.querySelectorAll("#central-comparison .comparison-card").length,3);ok(text(d,"central-comparison").includes("Demorar 1 año"));});
  test("2026 por debajo del umbral",function(){fillMain(d,{years:"38",months:"2"});ok(text(d,"main-results").includes("67 años"));});
  test("2027 y posteriores",function(){fillMain(d,{birth:"1962-06-15",asOf:"2027-06-15",years:"38",months:"6"});ok(text(d,"main-results").includes("65 años"));});
  test("proyección alcanza umbral después de 65",function(){fillMain(d,{birth:"1962-06-15",asOf:"2026-06-15",years:"37",months:"6",continued:"yes"});ok(text(d,"main-results").includes("15/06/2027"));ok(text(d,"warnings").includes("seguirás cotizando"));});
  test("sin continuidad no inventa cotización",function(){fillMain(d,{birth:"1962-06-15",asOf:"2026-06-15",years:"37",months:"6",continued:"no"});ok(text(d,"main-results").includes("15/06/2029"));});
  test("carencia insuficiente visible",function(){fillMain(d,{years:"14",months:"11"});ok(text(d,"main-results").includes("Cotización mínima no alcanzada"));});
  test("carencia específica desconocida visible",function(){fillMain(d,{specific:"unknown"});ok(text(d,"main-results").includes("Pendiente de confirmar"));});
  test("voluntaria no elegible sin mensaje de derecho",function(){fillMain(d,{years:"34",months:"11"});ok(!text(d,"main-results").includes("Podrías cumplir los requisitos cuantitativos"));});
  fillMain(d);
  test("GA4 mínimo y privado",function(){const event=(w.__events||[]).find(function(x){return x[0]==="event"&&x[1]==="retirement_calculated";});ok(event);eq(Object.keys(event[2]).join(","),"tool_name");eq(event[2].tool_name,"retirement");});
  test("edición deja resultado obsoleto oculto",function(){value(d,"contributionMonths","2");ok(d.getElementById("results").hidden);value(d,"contributionMonths","3");fillMain(d);});
  test("pensión 100 por ciento y formato español",function(){d.getElementById("pension-module").open=true;value(d,"baseRegulatory","2000,00");d.getElementById("calculate-pension").click();const actual=text(d,"pension-result");ok(actual.includes("100,00 %"),actual);ok(actual.includes("2.000,00 €"),actual);ok(actual.includes("14"),actual);});
  test("pensión al 50 por ciento",function(){fillMain(d,{years:"15",months:"0"});d.getElementById("pension-module").open=true;value(d,"baseRegulatory","2000");d.getElementById("calculate-pension").click();ok(text(d,"pension-result").includes("50,00 %"));fillMain(d);d.getElementById("pension-module").open=true;value(d,"baseRegulatory","2000");d.getElementById("calculate-pension").click();});
  test("base inválida no borra input",function(){value(d,"baseRegulatory","<img src=x onerror=alert(1)>");d.getElementById("calculate-pension").click();eq(d.getElementById("baseRegulatory").value,"<img src=x onerror=alert(1)>");eq(d.querySelectorAll("#pension-result img").length,0);ok(text(d,"baseRegulatory-error").length>0);value(d,"baseRegulatory","2000");d.getElementById("calculate-pension").click();});
  test("involuntaria potencial",function(){d.getElementById("involuntary-module").open=true;radio(d,"qualifyingCause","unknown");radio(d,"employmentRegistration","unknown");d.getElementById("calculate-involuntary").click();ok(text(d,"involuntary-result").includes("Podría existir"));ok(text(d,"involuntary-result").includes("Necesitas acreditar"));});
  test("involuntaria incumplida sin cero euros",function(){radio(d,"qualifyingCause","no");d.getElementById("calculate-involuntary").click();ok(text(d,"involuntary-result").includes("No se pueden confirmar"));ok(!text(d,"involuntary-result").includes("0,00 €"));});
  test("demorada un año porcentaje",function(){d.getElementById("deferred-module").open=true;radio(d,"deferredPeriod","12");radio(d,"effectiveDeferral","yes");radio(d,"deferredOption","PERCENTAGE");d.getElementById("calculate-deferred").click();ok(text(d,"deferred-result").includes("+4,00 %"));});
  test("demorada dos años",function(){radio(d,"deferredPeriod","24");d.getElementById("calculate-deferred").click();ok(text(d,"deferred-result").includes("+8,00 %"));});
  test("semestre adicional solo cuando es superior",function(){radio(d,"deferredPeriod","custom");const ordinary=d.querySelector("#main-results dd").textContent.split("/").reverse().join("-");value(d,"deferredDate",w.ImoancyJubilacionCore.addMonths(ordinary,31));d.getElementById("calculate-deferred").click();ok(text(d,"deferred-result").includes("+10,00 %"));});
  test("demorada semestre no elegible",function(){radio(d,"deferredPeriod","6");d.getElementById("calculate-deferred").click();ok(text(d,"deferred-result").includes("no se cumplen"));});
  test("pago único exige máximo",function(){radio(d,"deferredPeriod","24");radio(d,"deferredOption","LUMP_SUM");radio(d,"multiplePensions","no");radio(d,"internationalProration","no");d.getElementById("calculate-deferred").click();ok(text(d,"maximumPension-error").length>0);value(d,"maximumPension","45000");d.getElementById("calculate-deferred").click();ok(text(d,"deferred-result").includes("Pago único estimado"));ok(/\d\.\d{3},\d{2} €/.test(text(d,"deferred-result")));});
  test("mixta calculable",function(){radio(d,"deferredOption","MIXED");radio(d,"deferredPeriod","24");d.getElementById("calculate-deferred").click();ok(text(d,"deferred-result").includes("Modalidad mixta"));ok(text(d,"deferred-result").includes("Incremento porcentual"));});
  test("transición normativa",function(){fillMain(d,{birth:"1958-01-01",asOf:"2023-01-01",years:"45",months:"0"});d.getElementById("pension-module").open=true;value(d,"baseRegulatory","2000");d.getElementById("calculate-pension").click();d.getElementById("deferred-module").open=true;radio(d,"deferredPeriod","custom");value(d,"deferredDate","2025-08-01");radio(d,"effectiveDeferral","yes");radio(d,"deferredOption","MIXED");value(d,"maximumPension","45000");radio(d,"multiplePensions","no");radio(d,"internationalProration","no");d.getElementById("calculate-deferred").click();ok(text(d,"deferred-result").includes("transición normativa"),text(d,"deferred-result"));});
  test("sin almacenamiento ni red",function(){ok(!/localStorage|sessionStorage|fetch\(|XMLHttpRequest/.test(Array.from(d.scripts).map(function(s){return s.textContent;}).join("")));});
  test("sin scroll horizontal iframe",function(){ok(d.documentElement.scrollWidth<=d.documentElement.clientWidth);});
  [320,375,390,768,1024,1440].forEach(function(width){test("responsive "+width,function(){frame.width=String(width);void d.body.offsetWidth;ok(d.documentElement.scrollWidth<=d.documentElement.clientWidth,"scroll "+d.documentElement.scrollWidth+" > "+d.documentElement.clientWidth);});});
  test("reset completo conserva solo fecha técnica",function(){d.getElementById("reset-button").click();setTimeout(function(){test("reset asíncrono",function(){ok(d.getElementById("results").hidden);eq(d.getElementById("birthDate").value,"");ok(d.getElementById("asOfDate").value.length===10);});finish();},20);});
  function finish(){output.textContent="UI tests: "+passed+" PASS, "+failures.length+" FAIL";failures.forEach(function(x){output.appendChild(document.createElement("br"));output.appendChild(document.createTextNode("FAIL "+x));});document.body.dataset.complete="true";}
 });
}());
