(function () {
    "use strict";
    const C = typeof module === "object" && module.exports ? require("../js/core.js") : globalThis.FiniquitoCore;
    const resultados = [];
    function test(nombre, fundamento, fn) { try { fn(); resultados.push({ nombre, fundamento, ok: true }); } catch (e) { resultados.push({ nombre, fundamento, ok: false, error: e.message }); } }
    function eq(a, b, m) { if (a !== b) throw new Error(`${m || "valor"}: ${a} !== ${b}`); }
    function near(a, b, t, m) { if (Math.abs(a - b) > t) throw new Error(`${m || "valor"}: ${a} no está en ${b}±${t}`); }
    function ok(v, m) { if (!v) throw new Error(m || "condición falsa"); }
    function clone(v) { return JSON.parse(JSON.stringify(v)); }
    function base(overrides) {
        const x = {
            fechaInicio: "2025-01-01", fechaFin: "2025-12-31",
            salario: { tipo: "ANUAL", bruto: 36500 },
            ultimoPeriodo: { estrategia: "IMPORTE_EXPLICITO", importe: 0 },
            pagasExtra: { prorrateadas: true },
            vacaciones: { regimen: "NATURALES", diasAnuales: 30, disfrutados: 30, trasladados: 0, valorDiaExplicito: 100, periodosDevengo: [{ inicio: "2025-01-01", fin: "2025-12-31", diasDerechoPeriodoCompleto: 30 }] },
            variables: [], ajustes: [], preaviso: { aplicar: false }, extincion: { causa: "BAJA_VOLUNTARIA" }
        };
        return Object.assign(x, overrides || {});
    }
    function result(i, f, causa, extra) { const x = base({ fechaInicio: i, fechaFin: f, extincion: Object.assign({ causa }, extra || {}) }); x.vacaciones = { regimen: "NATURALES", diasAnuales: 30, disfrutados: 0, valorDiaExplicito: 0, periodosDevengo: [{ inicio: i, fin: f, diasDerechoPeriodoCompleto: 30 }] }; return C.calcular(x); }

    [
        ["fecha imposible", base({ fechaInicio: "2025-02-29" })],
        ["orden temporal", base({ fechaInicio: "2025-02-01", fechaFin: "2025-01-31" })],
        ["salario NaN", base({ salario: { tipo: "ANUAL", bruto: NaN } })],
        ["salario Infinity", base({ salario: { tipo: "ANUAL", bruto: Infinity } })],
        ["salario -Infinity", base({ salario: { tipo: "ANUAL", bruto: -Infinity } })],
        ["salario negativo", base({ salario: { tipo: "ANUAL", bruto: -1 } })],
        ["entrada vacía", {}]
    ].forEach(c => test(`INVALID ${c[0]}`, "Validación autónoma y finita.", () => { const r = C.calcular(c[1]); eq(r.status, "INVALID"); eq(r.total, null); }));

    test("ANUAL no exige numeroPagas", "Es información irrelevante si el anual ya está completo.", () => eq(C.calcular(base()).errores.length, 0));
    test("MENSUAL exige pagas", "La construcción anual mensual necesita su estructura.", () => eq(C.calcular(base({ salario: { tipo: "MENSUAL", bruto: 2000, extrasProrrateadas: false } })).status, "INVALID"));
    test("pagas >24", "Límite técnico documentado.", () => eq(C.calcular(base({ salario: { tipo: "MENSUAL", bruto: 2000, numeroPagas: 25, extrasProrrateadas: false } })).status, "INVALID"));
    test("más de 200 conceptos", "Límite técnico contra entradas abusivas.", () => eq(C.calcular(base({ variables: Array.from({ length: 201 }, (_, i) => ({ nombre: String(i), tipo: "OTRO", efecto: "SUMA", importe: 0 })) })).status, "INVALID"));

    test("fecha mismo día", "Intervalo civil inclusivo.", () => eq(C.fechas.diasInclusivos(C.fechas.parseFechaCivil("2025-01-01"), C.fechas.parseFechaCivil("2025-01-01")), 1));
    test("fin de mes", "Aritmética civil sin UTC.", () => eq(C.fechas.sumarDias(C.fechas.parseFechaCivil("2025-01-31"), 1).iso, "2025-02-01"));
    test("29 febrero", "Regla gregoriana.", () => eq(C.fechas.sumarDias(C.fechas.parseFechaCivil("2024-02-28"), 1).iso, "2024-02-29"));
    test("cambio de año", "Aritmética civil.", () => eq(C.fechas.sumarDias(C.fechas.parseFechaCivil("2025-12-31"), 1).iso, "2026-01-01"));
    [["2025-01-01","2025-01-31",1],["2025-01-01","2025-02-01",2],["2025-01-15","2025-02-14",1],["2025-01-15","2025-02-15",2],["2025-01-31","2025-02-28",2],["2025-01-01","2025-12-31",12],["2025-01-01","2026-01-01",13]].forEach(x => test(`meses ${x[0]}..${x[1]}`, "CGPJ: fracción residual es mes completo en arts. 53/56.", () => eq(C.fechas.mesesComputables(C.fechas.parseFechaCivil(x[0]), C.fechas.parseFechaCivil(x[1])), x[2])));

    test("anual completo no duplica", "El bruto anual ya contiene sus partidas.", () => eq(C.calcularBasesSalario({ tipo: "ANUAL", bruto: 30000, componentes: [{ id: "bonus", importeAnual: 2000, incluidoEnBruto: true, computableIndemnizacion: true }] }).anual.importe, 30000));
    test("anual base añade componente", "Solo se suma lo declarado no incluido y computable.", () => eq(C.calcularBasesSalario({ tipo: "ANUAL", bruto: 30000, componentes: [{ id: "plus", importeAnual: 2000, incluidoEnBruto: false, computableIndemnizacion: true }] }).anual.importe, 32000));
    test("componente no computable", "No entra en salario regulador.", () => eq(C.calcularBasesSalario({ tipo: "ANUAL", bruto: 30000, componentes: [{ id: "dietas", importeAnual: 2000, incluidoEnBruto: false, computableIndemnizacion: false }] }).anual.importe, 30000));
    test("id duplicado", "Defensa estructural contra doble conteo.", () => eq(C.calcular(base({ salario: { tipo: "ANUAL", bruto: 30000, componentes: [{ id: "x", importeAnual: 1, incluidoEnBruto: false, computableIndemnizacion: true }, { id: "x", importeAnual: 1, incluidoEnBruto: false, computableIndemnizacion: true }] } })).status, "INVALID"));
    test("variable sin período", "No inventa promedio representativo.", () => eq(C.calcular(base({ salario: { tipo: "ANUAL", bruto: 30000, componentes: [{ id: "comision", importeAnual: 1000, incluidoEnBruto: false, computableIndemnizacion: true, variable: true }] } })).status, "CONDITIONAL"));
    test("variable con período", "Importe agregado y período explícitos.", () => eq(C.calcular(base({ salario: { tipo: "ANUAL", bruto: 30000, componentes: [{ id: "comision", importeAnual: 1000, incluidoEnBruto: false, computableIndemnizacion: true, variable: true, periodoReferencia: { inicio: "2024-01-01", fin: "2024-12-31" } }] } })).basesSalariales.anual.importe, 31000));
    test("variable con período sin causa", "Un período válido no genera parcialidad específica.", () => { const r=C.calcular(base({salario:{tipo:"ANUAL",bruto:30000,componentes:[{id:"comision",nombre:"Comisión",importeAnual:1000,incluidoEnBruto:false,computableIndemnizacion:true,variable:true,periodoReferencia:{inicio:"2024-01-01",fin:"2024-12-31"}}]}})); ok(!r.total.causasParcialidad.some(c=>c.codigo==="VARIABLE_PERIODO_REFERENCIA_AUSENTE")); });
    test("variable sin período con causa específica", "Identifica variable, campo y motivo de la parcialidad.", () => { const r=C.calcular(base({salario:{tipo:"ANUAL",bruto:30000,componentes:[{id:"comision",nombre:"Comisión",importeAnual:1000,incluidoEnBruto:false,computableIndemnizacion:true,variable:true}]}})); const c=r.total.causasParcialidad.find(x=>x.codigo==="VARIABLE_PERIODO_REFERENCIA_AUSENTE"); eq(r.status,"CONDITIONAL");eq(r.total.esParcial,true);ok(c);eq(c.id,"comision");eq(c.nombre,"Comisión");eq(c.campo,"periodoReferencia"); });
    test("dos variables sin período generan dos causas", "Cada variable afectada permanece identificable.", () => { const r=C.calcular(base({salario:{tipo:"ANUAL",bruto:30000,componentes:[{id:"v1",nombre:"Variable 1",importeAnual:100,incluidoEnBruto:false,computableIndemnizacion:true,variable:true},{id:"v2",nombre:"Variable 2",importeAnual:200,incluidoEnBruto:false,computableIndemnizacion:true,variable:true}]}})); const cs=r.total.causasParcialidad.filter(c=>c.codigo==="VARIABLE_PERIODO_REFERENCIA_AUSENTE");eq(cs.length,2);ok(cs.some(c=>c.id==="v1")&&cs.some(c=>c.id==="v2")); });
    ["true",1,null,{},[]].forEach((v,i)=>test(`componente.variable no booleano ${i}`, "Un tipo incorrecto no puede evitar la exigencia del período.", () => { const x=base({salario:{tipo:"ANUAL",bruto:30000,componentes:[{id:"v",importeAnual:100,incluidoEnBruto:false,computableIndemnizacion:true,variable:v}]}});eq(C.calcular(x).status,"INVALID"); }));
    test("extras desiguales", "24.000 ordinario + 1.500 + 1.800 = 27.300.", () => eq(C.calcularBasesSalario({ tipo: "MENSUAL", bruto: 2000, numeroPagas: 14, extrasProrrateadas: false, cuantiasPagasExtraReguladoras: [1500, 1800] }).anual.importe, 27300));
    test("extras desconocidas condicionan", "La igualdad de pagas no es regla definitiva.", () => eq(C.calcular(base({ salario: { tipo: "MENSUAL", bruto: 2000, numeroPagas: 14, extrasProrrateadas: false } })).status, "CONDITIONAL"));
    test("prorrata más extras rechazada", "Impide duplicidad evidente.", () => eq(C.calcular(base({ salario: { tipo: "MENSUAL", bruto: 2000, numeroPagas: 14, extrasProrrateadas: true, cuantiasPagasExtraReguladoras: [1000, 1000] } })).status, "INVALID"));
    test("prorrata y paga pendiente condicionan", "Configuración contradictoria requiere revisar períodos.", () => { const x=base({ salario:{tipo:"MENSUAL",bruto:2000,numeroPagas:14,extrasProrrateadas:true},pagasExtra:{prorrateadas:false,pagas:[{nombre:"extra",cuantiaPeriodoCompleto:1000,periodoInicio:"2025-01-01",periodoFin:"2025-12-31"}]}}); eq(C.calcular(x).status,"CONDITIONAL"); });
    test("id regulador y pendiente condiciona", "El mismo id en dos dimensiones exige confirmar que no hay duplicación.", () => { const x=base({salario:{tipo:"ANUAL",bruto:30000,componentes:[{id:"bonus-2025",importeAnual:1000,incluidoEnBruto:true,computableIndemnizacion:true}]},variables:[{id:"bonus-2025",nombre:"bonus pendiente",tipo:"BONUS",efecto:"SUMA",importe:1000}]}); eq(C.calcular(x).status,"CONDITIONAL"); });
    test("componente no pendiente", "El regulador no se convierte automáticamente en deuda.", () => { const x=base({salario:{tipo:"ANUAL",bruto:30000,componentes:[{id:"plus",importeAnual:1200,incluidoEnBruto:true,computableIndemnizacion:true,pendientePago:false}]}}); eq(C.calcular(x).finiquito.componentesPendientes.importe,0); });
    test("componente pendiente explícito", "El saldo se añade una vez y no altera el regulador ya incluido.", () => { const x=base({salario:{tipo:"ANUAL",bruto:30000,componentes:[{id:"plus",importeAnual:1200,incluidoEnBruto:true,computableIndemnizacion:true,pendientePago:true,importePendiente:350}]}}); const r=C.calcular(x); eq(r.basesSalariales.anual.importe,30000); eq(r.finiquito.componentesPendientes.importe,350); eq(r.total.importeCalculado,350); });
    test("componente pendiente sin importe", "No inventa el saldo y lo identifica como concepto no calculado.", () => { const x=base({salario:{tipo:"ANUAL",bruto:30000,componentes:[{id:"plus",importeAnual:1200,incluidoEnBruto:true,computableIndemnizacion:true,pendientePago:true}]}}); const r=C.calcular(x); eq(r.status,"CONDITIONAL"); ok(r.total.conceptosNoCalculados.includes("componentePendiente:plus")); });
    test("componente pendiente cero", "Cero explícito es un saldo válido.", () => { const x=base({salario:{tipo:"ANUAL",bruto:30000,componentes:[{id:"plus",importeAnual:1200,incluidoEnBruto:true,computableIndemnizacion:true,pendientePago:true,importePendiente:0}]}}); eq(C.calcular(x).status,"OK"); });
    [NaN,Infinity,-Infinity,-1].forEach((v,i)=>test(`importe pendiente inválido ${i}`, "Debe ser finito y no negativo.", () => { const x=base({salario:{tipo:"ANUAL",bruto:30000,componentes:[{id:"plus",importeAnual:1200,incluidoEnBruto:true,computableIndemnizacion:true,pendientePago:true,importePendiente:v}]}}); eq(C.calcular(x).status,"INVALID"); }));
    test("pendiente duplicado en variables", "El mismo id no puede cobrarse por dos vías.", () => { const x=base({salario:{tipo:"ANUAL",bruto:30000,componentes:[{id:"plus",importeAnual:1200,incluidoEnBruto:true,computableIndemnizacion:true,pendientePago:true,importePendiente:100}]},variables:[{id:"plus",nombre:"plus",tipo:"OTRO",efecto:"SUMA",importe:100}]}); eq(C.calcular(x).status,"INVALID"); });
    test("salario diario trazable", "CGPJ: anual/365 con componentes y período.", () => { const b = C.calcularBasesSalario({ tipo: "ANUAL", bruto: 36500 }); eq(b.diarioIndemnizacion.importe, 100); ok(b.diarioIndemnizacion.referencia && b.diarioIndemnizacion.entradas.periodo); });

    test("salario explícito OK", "Cantidad conocida por el usuario.", () => eq(C.calcular(base({ ultimoPeriodo: { estrategia: "IMPORTE_EXPLICITO", importe: 123.45 } })).finiquito.salarioPendiente.status, "OK"));
    ["MENSUAL_30","MES_CALENDARIO","DIARIO_365"].forEach(e => test(`${e} condicionado`, "Estrategia avanzada, no equivalente jurídicamente.", () => { const cfg = { estrategia: e, diasPendientes: 1 }; eq(C.calcular(base({ ultimoPeriodo: cfg })).finiquito.salarioPendiente.status, "CONDITIONAL"); }));

    function paga(percibido) { return base({ pagasExtra: { prorrateadas: false, pagas: [{ nombre: "Extra", cuantiaPeriodoCompleto: 1200, periodoInicio: "2025-01-01", periodoFin: "2025-12-31", yaPercibido: percibido }] } }); }
    test("paga percibida menor", "1.200−200=1.000.", () => eq(C.calcular(paga(200)).finiquito.pagasExtra.importe, 1000));
    test("paga percibida igual", "Saldo cero sin deuda.", () => eq(C.calcular(paga(1200)).finiquito.pagasExtra.importe, 0));
    test("paga percibida superior", "No deduce; condiciona y conserva exceso.", () => { const r = C.calcular(paga(1300)); eq(r.status, "CONDITIONAL"); eq(r.finiquito.pagasExtra.importe, 0); eq(r.finiquito.pagasExtra.trazabilidad[0].excesoPercibidoNoDeducido, 100); });
    [NaN, Infinity, -Infinity, null, ""].forEach((v, i) => test(`paga opcional inválida ${i}`, "Aportado explícitamente debe ser finito.", () => eq(C.calcular(paga(v)).status, "INVALID")));
    test("paga ausente default cero", "Solo ausencia real activa default.", () => { const x = paga(0); delete x.pagasExtra.pagas[0].yaPercibido; eq(C.calcular(x).finiquito.pagasExtra.cobrado, 0); });
    test("ciclo julio-junio paga", "Solape inclusivo de ciclo explícito.", () => { const x = base({ fechaInicio: "2025-07-01", fechaFin: "2026-06-30", pagasExtra: { prorrateadas: false, pagas: [{ nombre: "Extra", cuantiaPeriodoCompleto: 1200, periodoInicio: "2025-07-01", periodoFin: "2026-06-30" }] }, vacaciones: { regimen: "NATURALES", diasAnuales: 30, disfrutados: 30, valorDiaExplicito: 0, periodosDevengo: [{ inicio: "2025-07-01", fin: "2026-06-30", diasDerechoPeriodoCompleto: 30 }] } }); eq(C.calcular(x).finiquito.pagasExtra.importe, 1200); });
    test("prorrata sin ciclos", "Ausencia o lista vacía son coherentes con prorrata.", () => { eq(C.calcular(base({pagasExtra:{prorrateadas:true}})).finiquito.pagasExtra.status,"OK"); eq(C.calcular(base({pagasExtra:{prorrateadas:true,pagas:[]}})).finiquito.pagasExtra.status,"OK"); });
    [NaN,Infinity,null,"",-1].forEach((v,i)=>test(`paga prorrateada inválida ${i}`, "La rama prorrateada también valida importes declarados.", () => { const x=base({pagasExtra:{prorrateadas:true,pagas:[{cuantiaPeriodoCompleto:v,periodoInicio:"2025-01-01",periodoFin:"2025-12-31"}]}}); eq(C.calcular(x).status,"INVALID"); }));
    test("paga prorrateada con fechas inválidas", "No oculta ciclos mal formados.", () => { const x=base({pagasExtra:{prorrateadas:true,pagas:[{cuantiaPeriodoCompleto:100,periodoInicio:"2025-02-30",periodoFin:"2025-12-31"}]}}); eq(C.calcular(x).status,"INVALID"); });
    test("paga prorrateada con percibido negativo", "También valida el cobro declarado aunque no liquide saldo.", () => { const x=base({pagasExtra:{prorrateadas:true,pagas:[{cuantiaPeriodoCompleto:100,yaPercibido:-1,periodoInicio:"2025-01-01",periodoFin:"2025-12-31"}]}}); eq(C.calcular(x).status,"INVALID"); });
    test("prorrata con ciclo válido condiciona", "Configuración incompatible sin sumar saldo.", () => { const x=base({pagasExtra:{prorrateadas:true,pagas:[{cuantiaPeriodoCompleto:100,periodoInicio:"2025-01-01",periodoFin:"2025-12-31"}]}}); const r=C.calcular(x); eq(r.status,"CONDITIONAL"); eq(r.finiquito.pagasExtra.importe,0); });

    function vac(i, f, cicloI, cicloF, disfrutados, extra) { return result(i, f, "BAJA_VOLUNTARIA").finiquito.vacaciones; }
    test("vacaciones año natural", "Ciclo completo explícito genera 30.", () => eq(vac("2025-01-01","2025-12-31").generadas, 30));
    test("vacaciones julio-junio", "Ciclo continuo completo genera 30 sin corte enero.", () => eq(vac("2024-07-01","2025-06-30").generadas, 30));
    test("vacaciones 29 febrero", "Ciclo explícito completo genera 30.", () => eq(vac("2024-02-29","2025-02-28").generadas, 30));
    test("vacaciones contrato corto", "30 de 365 días del ciclo generan 30×30/365.", () => { const x = base({ fechaInicio: "2025-01-01", fechaFin: "2025-01-30", vacaciones: { regimen: "NATURALES", diasAnuales: 30, disfrutados: 0, valorDiaExplicito: 0, periodosDevengo: [{ inicio: "2025-01-01", fin: "2025-12-31", diasDerechoPeriodoCompleto: 30 }] } }); near(C.calcular(x).finiquito.vacaciones.generadas, 30 * 30 / 365, 0.0001); });
    test("sin ciclo condiciona", "Estimación no finge certeza convencional.", () => { const x = base(); delete x.vacaciones.periodosDevengo; eq(C.calcular(x).finiquito.vacaciones.status, "CONDITIONAL"); });
    [NaN, Infinity, -Infinity, null, ""].forEach((v, i) => test(`trasladados inválido ${i}`, "Falsy no se convierte en cero.", () => eq(C.calcular(base({ vacaciones: Object.assign({}, base().vacaciones, { trasladados: v }) })).status, "INVALID")));
    test("saldo negativo condicionado", "Disfrute anticipado no crea deuda.", () => { const x = base(); x.vacaciones.disfrutados = 31; const r = C.calcular(x); eq(r.status, "CONDITIONAL"); eq(r.finiquito.vacaciones.importe, 0); near(r.finiquito.vacaciones.pendientes, -1, 0.0001); });
    test("vacaciones extraordinarias condicionan", "Control de dominio distinto del técnico.", () => { const x = base(); x.vacaciones.diasAnuales = 300; eq(C.calcular(x).status, "CONDITIONAL"); });
    test("ciclos vacacionales duplicados", "Un mismo tramo no puede devengarse dos veces.", () => { const x=base(); x.vacaciones.periodosDevengo.push(clone(x.vacaciones.periodosDevengo[0])); eq(C.calcular(x).status,"INVALID"); });
    test("ciclos vacacionales solapados", "El solape laboral invalida el devengo acumulado.", () => { const x=base(); x.vacaciones.periodosDevengo=[{inicio:"2025-01-01",fin:"2025-07-31",diasDerechoPeriodoCompleto:15},{inicio:"2025-07-01",fin:"2025-12-31",diasDerechoPeriodoCompleto:15}]; eq(C.calcular(x).status,"INVALID"); });
    test("ciclos vacacionales con hueco", "La cobertura incompleta se informa con fechas exactas.", () => { const x=base({fechaInicio:"2025-01-01",fechaFin:"2026-12-31"}); x.vacaciones={regimen:"NATURALES",diasAnuales:30,disfrutados:0,valorDiaExplicito:0,periodosDevengo:[{inicio:"2025-01-01",fin:"2025-12-31",diasDerechoPeriodoCompleto:30}]}; const v=C.calcular(x).finiquito.vacaciones; eq(v.status,"CONDITIONAL"); eq(v.generadas,30); eq(v.integridadPeriodos.huecos[0].inicio,"2026-01-01"); eq(v.integridadPeriodos.huecos[0].fin,"2026-12-31"); });
    test("ciclos vacacionales consecutivos", "Dos ciclos íntegros cubren dos años sin huecos.", () => { const x=base({fechaInicio:"2025-01-01",fechaFin:"2026-12-31"}); x.vacaciones={regimen:"NATURALES",diasAnuales:30,disfrutados:60,valorDiaExplicito:0,periodosDevengo:[{inicio:"2025-01-01",fin:"2025-12-31",diasDerechoPeriodoCompleto:30},{inicio:"2026-01-01",fin:"2026-12-31",diasDerechoPeriodoCompleto:30}]}; const v=C.calcular(x).finiquito.vacaciones; eq(v.status,"OK"); eq(v.generadas,60); eq(v.integridadPeriodos.diasCubiertos,730); });
    [0,0.01,0.5,1,29,30,31].forEach(d => test(`proyección saldo ${d}`, "Sin regla explícita no redondea ni inventa fecha.", () => { const x = base(); x.vacaciones.disfrutados = Math.max(0, 30 - d); x.vacaciones.trasladados = Math.max(0, d - 30); const p = C.calcular(x).finiquito.vacaciones.periodoPosteriorEstimado; if (d === 0) eq(p.diasProyectables, 0); else { eq(p.status, "CONDITIONAL"); eq(p.inicio, null); } }));
    [1,29,30,31].forEach(d => test(`proyección explícita ${d}`, "TGSS: inicia al día siguiente y dura días naturales enteros declarados.", () => { const x = base(); x.vacaciones.disfrutados = Math.max(0, 30 - d); x.vacaciones.trasladados = Math.max(0, d - 30); x.vacaciones.proyeccion = { reglaExplicita: true, diasProyectables: d, unidadOrigen:"NATURALES", unidadDestino:"NATURALES", referencia: "días reconocidos en liquidación" }; const p = C.calcular(x).finiquito.vacaciones.periodoPosteriorEstimado; eq(p.inicio, "2026-01-01"); eq(p.fin, C.fechas.sumarDias(C.fechas.parseFechaCivil("2025-12-31"), d).iso); }));
    test("proyección incoherente sin transformación", "No asigna fechas cuando 30 días de saldo se convierten en uno sin regla.", () => { const x=base(); x.vacaciones.disfrutados=0; x.vacaciones.proyeccion={reglaExplicita:true,diasProyectables:1,referencia:"liquidación"}; const p=C.calcular(x).finiquito.vacaciones.periodoPosteriorEstimado; eq(p.status,"CONDITIONAL"); eq(p.inicio,null); });
    test("proyección transformada documentada", "Una transformación divergente queda trazada y condicionada.", () => { const x=base(); x.vacaciones.disfrutados=0; x.vacaciones.proyeccion={reglaExplicita:true,diasProyectables:1,unidadOrigen:"NATURALES",unidadDestino:"NATURALES",referencia:"liquidación",tipoTransformacion:"CONVERSION_CONVENIO",justificacion:"Regla aportada por el usuario"}; const p=C.calcular(x).finiquito.vacaciones.periodoPosteriorEstimado; eq(p.status,"CONDITIONAL"); eq(p.inicio,"2026-01-01"); eq(p.tipoTransformacion,"CONVERSION_CONVENIO"); });
    test("proyección fraccionaria requiere transformación", "Un saldo no entero no se redondea implícitamente.", () => { const x=base(); x.vacaciones.disfrutados=29.5; x.vacaciones.proyeccion={reglaExplicita:true,diasProyectables:1,referencia:"liquidación"}; eq(C.calcular(x).finiquito.vacaciones.periodoPosteriorEstimado.inicio,null); });
    test("ciclo plurianual con derecho explícito", "Dos años solo generan 60 si el ciclo declara ese derecho completo.", () => { const x=base({fechaFin:"2026-12-31"}); x.vacaciones={regimen:"NATURALES",diasAnuales:30,disfrutados:60,valorDiaExplicito:0,periodosDevengo:[{inicio:"2025-01-01",fin:"2026-12-31",diasDerechoPeriodoCompleto:60}]}; const v=C.calcular(x).finiquito.vacaciones; eq(v.status,"OK"); eq(v.generadas,60); });
    test("ciclo plurianual sin derecho condiciona", "La tasa anual estima 60 sin fingir que el ciclo arbitrario es una anualidad.", () => { const x=base({fechaFin:"2026-12-31"}); x.vacaciones={regimen:"NATURALES",diasAnuales:30,disfrutados:0,valorDiaExplicito:0,periodosDevengo:[{inicio:"2025-01-01",fin:"2026-12-31"}]}; const r=C.calcular(x),v=r.finiquito.vacaciones; eq(v.status,"CONDITIONAL"); eq(v.generadas,60); ok(r.total.causasParcialidad.some(c=>c.codigo==="VACACIONES_DERECHO_PERIODO_NO_DECLARADO")); });
    test("dos semestres con derechos explícitos", "Dos derechos semestrales de 15 forman 30, no 60.", () => { const x=base(); x.vacaciones={regimen:"NATURALES",diasAnuales:30,disfrutados:30,valorDiaExplicito:0,periodosDevengo:[{inicio:"2025-01-01",fin:"2025-06-30",diasDerechoPeriodoCompleto:15},{inicio:"2025-07-01",fin:"2025-12-31",diasDerechoPeriodoCompleto:15}]}; const v=C.calcular(x).finiquito.vacaciones; eq(v.status,"OK"); eq(v.generadas,30); });
    test("dos semestres sin derechos condicionan", "No asigna automáticamente 30 a cada semestre.", () => { const x=base(); x.vacaciones={regimen:"NATURALES",diasAnuales:30,disfrutados:30,valorDiaExplicito:0,periodosDevengo:[{inicio:"2025-01-01",fin:"2025-06-30"},{inicio:"2025-07-01",fin:"2025-12-31"}]}; const v=C.calcular(x).finiquito.vacaciones; eq(v.status,"CONDITIONAL"); eq(v.generadas,30); });
    test("ciclo anual bisiesto explícito", "El derecho completo del ciclo bisiesto sigue siendo 30.", () => { const x=base({fechaInicio:"2024-01-01",fechaFin:"2024-12-31"}); x.vacaciones={regimen:"NATURALES",diasAnuales:30,disfrutados:30,valorDiaExplicito:0,periodosDevengo:[{inicio:"2024-01-01",fin:"2024-12-31",diasDerechoPeriodoCompleto:30}]}; eq(C.calcular(x).finiquito.vacaciones.generadas,30); });
    test("proyección laborable no inventa calendario", "La igualdad numérica conserva laborables sin convertirlos en naturales.", () => { const x=base(); x.vacaciones={regimen:"LABORABLES",diasAnuales:22,disfrutados:0,valorDiaExplicito:100,periodosDevengo:[{inicio:"2025-01-01",fin:"2025-12-31",diasDerechoPeriodoCompleto:22}],proyeccion:{reglaExplicita:true,diasProyectables:22,unidadOrigen:"LABORABLES",unidadDestino:"LABORABLES",referencia:"liquidación"}}; const p=C.calcular(x).finiquito.vacaciones.periodoPosteriorEstimado; eq(p.status,"CONDITIONAL"); eq(p.diasProyectables,22); eq(p.unidadDestino,"LABORABLES"); eq(p.inicio,null); eq(p.fin,null); });
    test("proyección laborable transformada a natural", "Conserva origen/destino y condiciona una transformación no verificable.", () => { const x=base(); x.vacaciones={regimen:"LABORABLES",diasAnuales:22,disfrutados:0,valorDiaExplicito:100,periodosDevengo:[{inicio:"2025-01-01",fin:"2025-12-31",diasDerechoPeriodoCompleto:22}],proyeccion:{reglaExplicita:true,diasProyectables:30,unidadOrigen:"LABORABLES",unidadDestino:"NATURALES",referencia:"calendario aportado",tipoTransformacion:"CALENDARIO_EXTERNO",justificacion:"Conversión declarada por el usuario"}}; const p=C.calcular(x).finiquito.vacaciones.periodoPosteriorEstimado; eq(p.status,"CONDITIONAL"); eq(p.unidadOrigen,"LABORABLES"); eq(p.unidadDestino,"NATURALES"); eq(p.fin,"2026-01-30"); });

    [
        ["período variable vacío",{}], ["período variable solo inicio",{inicio:"2025-01-01"}], ["período variable solo fin",{fin:"2025-12-31"}],
        ["período variable fecha inválida",{inicio:"2025-02-30",fin:"2025-12-31"}], ["período variable invertido",{inicio:"2025-12-31",fin:"2025-01-01"}]
    ].forEach(c=>test(c[0], "Una estructura aportada pero inválida no acredita representatividad.", () => { const x=base({salario:{tipo:"ANUAL",bruto:30000,componentes:[{id:"v",importeAnual:1000,incluidoEnBruto:false,computableIndemnizacion:true,variable:true,periodoReferencia:c[1]}]}}); eq(C.calcular(x).status,"INVALID"); }));

    [{},"componentes",1,null].forEach((v,i)=>test(`componentes no array ${i}`, "Toda colección se valida antes de filter/map.", () => { const x=base(); x.salario.componentes=v; eq(C.calcular(x).status,"INVALID"); }));
    [null,"x",1,{}].forEach((v,i)=>test(`elemento componente inválido ${i}`, "Un elemento inválido produce estado controlado.", () => { const x=base(); x.salario.componentes=[v]; eq(C.calcular(x).status,"INVALID"); }));
    [null,"x",1,{}].forEach((v,i)=>test(`elemento componente mensual inválido ${i}`, "La reconstrucción mensual tampoco accede a propiedades de elementos inválidos.", () => { const x=base(); x.salario={tipo:"MENSUAL",bruto:2000,numeroPagas:14,extrasProrrateadas:false,cuantiasPagasExtraReguladoras:[1500,1800],componentes:[v]}; eq(C.calcular(x).status,"INVALID"); }));
    ["variables","ajustes"].forEach(k=>[null,"x",1,{}].forEach((v,i)=>test(`${k} no array ${i}`, "Las colecciones de conceptos no provocan excepciones.", () => { const x=base(); x[k]=v; eq(C.calcular(x).status,"INVALID"); })));
    [null,"x",1,{}].forEach((v,i)=>test(`periodosDevengo no array ${i}`, "La colección vacacional mal tipada se rechaza.", () => { const x=base(); x.vacaciones.periodosDevengo=v; eq(C.calcular(x).status,"INVALID"); }));
    [null,"x",1,{}].forEach((v,i)=>test(`paga elemento inválido ${i}`, "La colección de pagas falla de forma controlada.", () => { const x=base({pagasExtra:{prorrateadas:false,pagas:[v]}}); eq(C.calcular(x).status,"INVALID"); }));

    test("id de paga duplicado", "La identidad estable repetida impide doble suma.", () => { const p={id:"extra-verano",nombre:"Extra",cuantiaPeriodoCompleto:1200,periodoInicio:"2025-01-01",periodoFin:"2025-12-31"}; const x=base({pagasExtra:{prorrateadas:false,pagas:[p,clone(p)]}}); eq(C.calcular(x).status,"INVALID"); });
    test("pagas idénticas sin id condicionan", "Una repetición literal no se suma silenciosamente con OK.", () => { const p={nombre:"Extra",cuantiaPeriodoCompleto:1200,periodoInicio:"2025-01-01",periodoFin:"2025-12-31"}; const r=C.calcular(base({pagasExtra:{prorrateadas:false,pagas:[p,clone(p)]}})); eq(r.status,"CONDITIONAL"); eq(r.finiquito.pagasExtra.importe,2400); ok(r.total.causasParcialidad.some(c=>c.codigo==="PAGA_POSIBLE_DUPLICIDAD")); });
    test("pagas equivalentes por defaults condicionan", "Ausencia de percibido y cero explícito representan la misma configuración económica.", () => { const a={nombre:"Extra",cuantiaPeriodoCompleto:1200,periodoInicio:"2025-01-01",periodoFin:"2025-12-31"},b=Object.assign({},a,{yaPercibido:0}); eq(C.calcular(base({pagasExtra:{prorrateadas:false,pagas:[a,b]}})).status,"CONDITIONAL"); });
    test("pagas distintas mismo ciclo", "Dos identidades diferentes pueden compartir devengo.", () => { const x=base({pagasExtra:{prorrateadas:false,pagas:[{id:"verano",nombre:"Verano",cuantiaPeriodoCompleto:1200,periodoInicio:"2025-01-01",periodoFin:"2025-12-31"},{id:"navidad",nombre:"Navidad",cuantiaPeriodoCompleto:1200,periodoInicio:"2025-01-01",periodoFin:"2025-12-31"}]}}); eq(C.calcular(x).finiquito.pagasExtra.status,"OK"); });

    [["2025-01-01","2025-01-01",1],["2025-01-01","2025-01-02",2],["2025-01-01","2025-01-15",15],["2025-01-01","2025-01-29",29],["2025-01-01","2025-01-30",30],["2025-01-01","2025-01-31",31],["2025-01-01","2025-12-31",365],["2025-01-01","2026-12-31",730]].forEach(x => test(`temporal ${x[2]} días`, "CGPJ: salario diario × días reales × módulo/365.", () => near(result(x[0], x[1], "FIN_CONTRATO_TEMPORAL_INDEMNIZABLE").indemnizacion.importe, Math.round((100 * x[2] * 12 / 365) * 100) / 100, 0.001)));
    [["2011-01-01","2011-12-31",8],["2012-01-01","2012-12-30",9],["2013-01-01","2013-12-31",10],["2014-01-01","2014-12-31",11],["2015-01-01","2015-12-31",12]].forEach(x => test(`temporal histórico ${x[0]}`, "DT 8 ET, módulo según celebración.", () => { const r = result(x[0], x[1], "FIN_CONTRATO_TEMPORAL_INDEMNIZABLE").indemnizacion; eq(r.diasPorAnio, x[2]); near(r.importe, x[2] * 100, 0.01); }));
    test("temporal anterior 04/03/2001", "DT 8.2: no inventa importe.", () => eq(result("2001-03-03","2002-03-02","FIN_CONTRATO_TEMPORAL_INDEMNIZABLE").status, "UNSUPPORTED"));
    test("formativo excluido", "ET 49.1.c.", () => eq(result("2025-01-01","2025-12-31","FIN_CONTRATO_FORMATIVO").indemnizacion.importe, 0));
    test("sustitución excluida", "ET 49.1.c.", () => eq(result("2025-01-01","2025-12-31","FIN_CONTRATO_SUSTITUCION").indemnizacion.importe, 0));

    test("objetivo un año", "20 días × 100 €.", () => eq(result("2025-01-01","2025-12-31","DESPIDO_OBJETIVO").indemnizacion.importe, 2000));
    [["2008-01-01","2025-11-30",215*20/12],["2008-01-01","2025-12-31",360],["2008-01-01","2026-01-01",360]].forEach((x,i) => test(`tope objetivo ${i}`, "215 meses inferior; 216 exacto; superior topado.", () => near(result(x[0],x[1],"DESPIDO_OBJETIVO").indemnizacion.diasIndemnizatorios,x[2],1e-9)));
    test("improcedencia requiere confirmación", "El motor no califica el despido.", () => eq(result("2025-01-01","2025-12-31","DESPIDO_IMPROCEDENTE").indemnizacion.status, "CONDITIONAL"));
    function imp(i,f){ return result(i,f,"DESPIDO_IMPROCEDENTE",{improcedenciaReconocidaOSimulada:true}).indemnizacion; }
    test("inicio exacto corte", "12/02/2012 no tiene tramo 45.", () => ok(!imp("2012-02-12","2013-02-11").tramos));
    test("inicio día anterior corte", "11/02/2012 crea ambos tramos.", () => { const r=imp("2012-02-11","2012-02-12"); eq(r.tramos.meses45,1); eq(r.tramos.meses33,1); eq(r.diasIndemnizatorios,6.5); });
    test("tramo 45 exactamente 720", "192×3,75=720.", () => eq(imp("1996-02-12","2012-02-11").diasIndemnizatorios,720));
    test("primer escalón sobre 720", "193×3,75=723,75.", () => eq(imp("1996-01-12","2012-02-11").diasIndemnizatorios,723.75));
    test("tramo >720 ignora posterior", "El máximo queda en lo devengado al corte.", () => eq(imp("1996-01-12","2030-12-31").diasIndemnizatorios,723.75));
    test("máximo transitorio 1260", "336×3,75=1260.", () => eq(imp("1984-02-12","2012-02-11").diasIndemnizatorios,1260));
    test("teórico superior a 1260", "42 mensualidades es límite absoluto.", () => eq(imp("1970-01-01","2030-12-31").diasIndemnizatorios,1260));
    test("improcedente post inferior 720", "261 meses×2,75=717,75.", () => eq(imp("2012-02-12","2033-11-11").diasIndemnizatorios,717.75));
    test("improcedente post exacto 720", "Se topa exactamente.", () => eq(imp("2012-02-12","2033-12-11").diasIndemnizatorios,720));
    test("improcedente post superior", "No supera 720.", () => eq(imp("2012-02-12","2040-12-31").diasIndemnizatorios,720));

    test("preaviso sin fuente", "No basta afirmar que es explícito.", () => { const x=base(); x.preaviso={ aplicar:true,diasExigibles:15,diasDados:0,importeDia:100,parteObligada:"PERSONA_TRABAJADORA",causaExtincion:"BAJA_VOLUNTARIA" }; eq(C.calcular(x).finiquito.preaviso.status,"CONDITIONAL"); });
    test("preaviso causa contradictoria", "No aplica ajuste de otra causa.", () => { const x=base(); x.preaviso={ aplicar:true,diasExigibles:15,diasDados:0,importeDia:100,parteObligada:"PERSONA_TRABAJADORA",causaExtincion:"DESPIDO_OBJETIVO",tipoFuente:"CONVENIO",referenciaFuente:"Convenio X art. 1" }; eq(C.calcular(x).finiquito.preaviso.importe,0); });
    test("preaviso sin tratamiento", "La parte obligada no determina por sí sola el signo económico.", () => { const x=base(); x.preaviso={ aplicar:true,diasExigibles:15,diasDados:10,importeDia:100,parteObligada:"PERSONA_TRABAJADORA",causaExtincion:"BAJA_VOLUNTARIA",tipoFuente:"CONVENIO",referenciaFuente:"Convenio X art. 1" }; const p=C.calcular(x).finiquito.preaviso; eq(p.status,"CONDITIONAL"); eq(p.importe,0); });
    test("preaviso tratamiento desconocido", "El enum económico es cerrado.", () => { const x=base(); x.preaviso={ aplicar:true,diasExigibles:15,diasDados:10,importeDia:100,parteObligada:"PERSONA_TRABAJADORA",causaExtincion:"BAJA_VOLUNTARIA",tipoFuente:"CONVENIO",referenciaFuente:"Convenio X art. 1",tratamientoEconomico:"OTRO" }; eq(C.calcular(x).status,"INVALID"); });
    test("preaviso fundado", "Datos, referencia y deducción explícita completos.", () => { const x=base(); x.preaviso={ aplicar:true,diasExigibles:15,diasDados:10,importeDia:100,parteObligada:"PERSONA_TRABAJADORA",causaExtincion:"BAJA_VOLUNTARIA",tipoFuente:"CONVENIO",referenciaFuente:"Convenio X art. 1",tratamientoEconomico:"DEDUCCION" }; eq(C.calcular(x).finiquito.preaviso.importe,-500); });
    test("preaviso abono explícito", "El tratamiento, no la parte, fija el signo.", () => { const x=base(); x.preaviso={ aplicar:true,diasExigibles:15,diasDados:10,importeDia:100,parteObligada:"PERSONA_TRABAJADORA",causaExtincion:"BAJA_VOLUNTARIA",tipoFuente:"CONVENIO",referenciaFuente:"Convenio X art. 1",tratamientoEconomico:"ABONO" }; eq(C.calcular(x).finiquito.preaviso.importe,500); });
    [
        {}, [], true, false, "false", 0, null,
        {aplicar:"false"},{aplicar:"true"},{aplicar:0},{aplicar:1},{aplicar:null},{aplicar:undefined}
    ].forEach((v,i)=>test(`preaviso estructura adversarial ${i}`, "Solo aplicar booleano dentro de un objeto expresa una decisión.", () => { const x=base();x.preaviso=v;eq(C.calcular(x).status,"INVALID"); }));
    test("preaviso ausente condiciona", "La ausencia no se presenta como decisión expresa.", () => { const x=base();delete x.preaviso;const r=C.calcular(x);eq(r.status,"CONDITIONAL");eq(r.finiquito.preaviso.importe,0); });
    test("preaviso false estricto", "Solo el booleano false expresa ausencia de ajuste.", () => { const r=C.calcular(base({preaviso:{aplicar:false}}));eq(r.finiquito.preaviso.status,"OK");eq(r.finiquito.preaviso.importe,0); });
    ["true",1,null,{},[]].forEach((v,i)=>test(`normativaEspecifica no booleana ${i}`, "No convierte un tipo incorrecto en aplicación del régimen general.", () => { const x=base({extincion:{causa:"FIN_CONTRATO_TEMPORAL_INDEMNIZABLE",normativaEspecifica:v}});eq(C.calcular(x).status,"INVALID"); }));
    ["true",1,null,{},[]].forEach((v,i)=>test(`improcedencia confirmación no booleana ${i}`, "La confirmación jurídica debe ser booleana.", () => { const x=base({extincion:{causa:"DESPIDO_IMPROCEDENTE",improcedenciaReconocidaOSimulada:v}});eq(C.calcular(x).status,"INVALID"); }));

    test("total OK no parcial", "La suma enumera partidas mostradas.", () => { const r=C.calcular(base()); eq(r.status,"OK"); eq(r.total.esParcial,false); eq(r.total.importeCalculado,0); eq(r.total.partidas.length,8); });
    test("total CONDITIONAL parcial", "No se presenta como definitivo.", () => { const x=base(); delete x.pagasExtra; const r=C.calcular(x); eq(r.status,"CONDITIONAL"); eq(r.total.esParcial,true); ok(r.total.conceptosNoCalculados.includes("pagasExtraordinarias")); });
    test("total UNSUPPORTED parcial", "Conserva solo importe calculado y marca falta.", () => { const r=result("2000-01-01","2001-01-01","FIN_CONTRATO_TEMPORAL_INDEMNIZABLE"); eq(r.status,"UNSUPPORTED"); eq(r.total.esParcial,true); ok(r.total.conceptosNoCalculados.includes("indemnizacion")); });
    test("total INVALID nulo", "No hay cifra económicamente presentable.", () => eq(C.calcular(base({ salario:{tipo:"ANUAL",bruto:NaN} })).total,null));
    test("redondeo por partidas", "Total mostrado suma exactamente céntimos mostrados.", () => { const x=base({ ultimoPeriodo:{estrategia:"IMPORTE_EXPLICITO",importe:10.005},variables:[{nombre:"x",tipo:"OTRO",efecto:"SUMA",importe:20.005}] }); const r=C.calcular(x); const suma=r.total.partidas.reduce((s,p)=>C.dinero.desdeCentimos(C.dinero.aCentimos(s)+C.dinero.aCentimos(p.importe)),0); eq(r.total.importeCalculado,suma); });
    [[1.005,1.01],[-1.005,-1.01],[2.675,2.68],[-2.675,-2.68]].forEach(x=>test(`redondeo HALF_UP ${x[0]}`, "El redondeo monetario es simétrico respecto de cero.", () => eq(C.dinero.redondearMoneda(x[0]),x[1])));
    [[2.135,2.14],[2.175,2.18],[2.385,2.39],[4.015,4.02],[4.145,4.15],[10.115,10.12]].forEach(x=>test(`redondeo binario adversarial ${x[0]}`, "La representación IEEE-754 se interpreta mediante su decimal normalizado.", () => { eq(C.dinero.redondearMoneda(x[0]),x[1]); eq(C.dinero.redondearMoneda(-x[0]),-x[1]); }));
    test("propiedad HALF_UP en milésimas", "Referencia independiente mediante aritmética entera sobre n/1000.", () => { for(let n=0;n<=200000;n+=1){const v=n/1000,esperado=Math.floor(n/10+0.5)/100;eq(C.dinero.redondearMoneda(v),esperado,`positivo n=${n}`);eq(C.dinero.redondearMoneda(-v),-esperado,`negativo n=${n}`);} });
    [[0.004,0], [0.005,0.01], [0.006,0.01], [-0.004,0], [-0.005,-0.01], [-0.006,-0.01]].forEach(x=>test(`redondeo milésimas ${x[0]}`, "Los dos signos comparten la misma frontera de medio céntimo.", () => eq(C.dinero.redondearMoneda(x[0]),x[1])));
    test("redondeo próximo al límite", "La normalización central conserva HALF_UP y simetría en importes altos permitidos.", () => { const v=C.normativa.limitesEntrada.importeAbsolutoMaximo-0.005; eq(C.dinero.redondearMoneda(v),C.normativa.limitesEntrada.importeAbsolutoMaximo); eq(C.dinero.redondearMoneda(v),-C.dinero.redondearMoneda(-v)); });
    test("ajustes opuestos cancelan", "Importes opuestos redondeados producen total exactamente cero.", () => { const x=base({ajustes:[{nombre:"a",tipo:"OTRO",efecto:"SUMA",importe:1.005},{nombre:"b",tipo:"OTRO",efecto:"RESTA",importe:1.005}]}); eq(C.calcular(x).total.importeCalculado,0); });
    test("parcialidad siempre explicada", "Todo resultado parcial no inválido expone al menos una causa estructurada.", () => { const casos=[]; let x=base(); delete x.pagasExtra; casos.push(x); x=base(); delete x.vacaciones.periodosDevengo; casos.push(x); x=base(); x.salario.componentes=[{id:"v",importeAnual:100,incluidoEnBruto:true,computableIndemnizacion:true}];x.variables=[{id:"v",nombre:"v",tipo:"BONUS",efecto:"SUMA",importe:10}];casos.push(x); x=base();x.extincion={causa:"NULIDAD"};casos.push(x); casos.forEach((entrada,i)=>{const r=C.calcular(entrada);ok(r.status==="CONDITIONAL"||r.status==="UNSUPPORTED",`estado caso ${i}`);eq(r.total.esParcial,true);ok(r.total.causasParcialidad.length>0,`causas caso ${i}`);ok(r.total.conceptosNoCalculados.length>0,`conceptos caso ${i}`);}); });

    test("entrada sin mutación profunda", "El motor puro no escribe en la entrada.", () => { const x=base(), antes=JSON.stringify(x); C.calcular(x); eq(JSON.stringify(x),antes); });
    test("normativa congelada profunda", "Parámetros no mutables.", () => ok(Object.isFrozen(C.normativa)&&Object.isFrozen(C.normativa.referencias.temporal.escalaPorFechaCelebracion)));
    test("ejecuciones idénticas", "Determinismo.", () => { const x=base(); eq(JSON.stringify(C.calcular(x)),JSON.stringify(C.calcular(x))); });
    test("ejecuciones intercaladas", "Sin estado global entre cálculos.", () => { const a=base(), esperado=JSON.stringify(C.calcular(a)); C.calcular(paga(1300)); eq(JSON.stringify(C.calcular(a)),esperado); });
    test("sin DOM", "Calcula sin document/window.", () => eq(C.calcular(base()).errores.length,0));
    test("sin Date UTC", "Las utilidades expuestas son aritmética civil.", () => { const fuente=Object.values(C.fechas).map(String).join(" "); ok(!/Date\s*\.|new Date|UTC/.test(fuente)); });

    test("trazabilidad indemnización", "Fórmula, inputs, referencia, redondeo y tope.", () => { const t=result("2025-01-01","2025-12-31","DESPIDO_OBJETIVO").indemnizacion.trazabilidad[0]; ok(t.formula&&t.entradas&&t.referencia&&t.redondeo&&Object.prototype.hasOwnProperty.call(t,"limiteAplicado")); });
    test("trazabilidad temporal", "Expone días reales y módulo histórico.", () => { const t=result("2014-01-01","2014-12-31","FIN_CONTRATO_TEMPORAL_INDEMNIZABLE").indemnizacion.trazabilidad[0]; eq(t.entradas.diasPorAnio,11); eq(t.metodo,"SALARIO_DIARIO_X_DIAS_REALES_X_MODULO_ENTRE_365"); });
    test("trazabilidad vacaciones", "Expone ciclos y fórmula de devengo.", () => ok(C.calcular(base()).finiquito.vacaciones.trazabilidad[0].entradas.periodosUsados.length===1));

    const pass=resultados.filter(r=>r.ok).length, fail=resultados.length-pass, resumen={total:resultados.length,pass,fail,resultados};
    if(typeof module==="object"&&module.exports){if(require.main===module){resultados.forEach(r=>console.log(`${r.ok?"PASS":"FAIL"} ${r.nombre}${r.error?` — ${r.error}`:""}`));console.log(`TOTAL ${resultados.length} PASS ${pass} FAIL ${fail}`);if(fail)process.exitCode=1;}module.exports=resumen;}else globalThis.FiniquitoTestResults=resumen;
})();
