"use strict";

(function (root) {
    const N = root.ImoancyJubilacionNormativa2026;
    if (!N) throw new Error("Missing ImoancyJubilacionNormativa2026");
    const STATUS = Object.freeze({ OK:"OK", INVALID_INPUT:"INVALID_INPUT", OUT_OF_SCOPE:"OUT_OF_SCOPE", REQUIRES_SPECIAL_ANALYSIS:"REQUIRES_SPECIAL_ANALYSIS", MINIMUM_CONTRIBUTION_NOT_MET:"MINIMUM_CONTRIBUTION_NOT_MET", SPECIFIC_CARENCE_UNKNOWN:"SPECIFIC_CARENCE_UNKNOWN", POTENTIALLY_ELIGIBLE:"POTENTIALLY_ELIGIBLE", NOT_ELIGIBLE:"NOT_ELIGIBLE" });
    const WARNING = Object.freeze({ PROJECTED_CONTINUED_CONTRIBUTIONS:"PROJECTED_CONTINUED_CONTRIBUTIONS", BASE_REGULATORY_PROVIDED_BY_USER:"BASE_REGULATORY_PROVIDED_BY_USER", PENSION_MAXIMUM_NOT_APPLIED:"PENSION_MAXIMUM_NOT_APPLIED", PENSION_MINIMUM_NOT_EVALUATED:"PENSION_MINIMUM_NOT_EVALUATED", SPECIFIC_CARENCE_NOT_CONFIRMED:"SPECIFIC_CARENCE_NOT_CONFIRMED", INVOLUNTARY_LEGAL_CAUSE_NOT_VERIFIED:"INVOLUNTARY_LEGAL_CAUSE_NOT_VERIFIED", ADVANCED_BASE_REQUIRES_IPC_AND_GAP_RULES:"ADVANCED_BASE_REQUIRES_IPC_AND_GAP_RULES" });
    const DEFERRED_OPTION = Object.freeze({ PERCENTAGE:"PERCENTAGE", LUMP_SUM:"LUMP_SUM", MIXED:"MIXED" });
    const REGIME = Object.freeze({ GENERAL_STANDARD:"GENERAL_STANDARD" });

    function invalid(field, code) { return { status:STATUS.INVALID_INPUT, errors:[{field:field,code:code}] }; }
    function finiteNumber(x) { return typeof x === "number" && Number.isFinite(x); }
    function integer(x) { return Number.isInteger(x); }
    function parseDate(value) {
        if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return null;
        const p=value.split("-").map(Number), d=new Date(Date.UTC(p[0],p[1]-1,p[2]));
        return d.getUTCFullYear()===p[0]&&d.getUTCMonth()===p[1]-1&&d.getUTCDate()===p[2]?d:null;
    }
    function iso(d) { return d.getUTCFullYear()+"-"+String(d.getUTCMonth()+1).padStart(2,"0")+"-"+String(d.getUTCDate()).padStart(2,"0"); }
    function daysInMonth(y,m) { return new Date(Date.UTC(y,m+1,0)).getUTCDate(); }
    function addMonths(value, months) {
        const d=typeof value==="string"?parseDate(value):value;
        if (!d || !integer(months)) return null;
        const total=d.getUTCFullYear()*12+d.getUTCMonth()+months, y=Math.floor(total/12), m=((total%12)+12)%12;
        return iso(new Date(Date.UTC(y,m,Math.min(d.getUTCDate(),daysInMonth(y,m)))));
    }
    function addYears(value, years) { return addMonths(value,years*12); }
    function compare(a,b) { return a<b?-1:a>b?1:0; }
    function completeMonthsBetween(a,b) {
        const x=parseDate(a),y=parseDate(b); if(!x||!y||compare(a,b)>0)return null;
        let n=(y.getUTCFullYear()-x.getUTCFullYear())*12+y.getUTCMonth()-x.getUTCMonth();
        if (compare(addMonths(a,n),b)>0)n-=1; return n;
    }
    function ageOn(birth,date) { const m=completeMonthsBetween(birth,date); return m===null?null:{years:Math.floor(m/12),months:m%12,totalMonths:m}; }
    function ruleForYear(year) { let r=null; N.ordinaryAgeCalendar.forEach(function(x){if(year>=x.fromYear)r=x;}); return r; }
    function projectedMonths(input,date) {
        let total=input.contributedMonthsAsOfDate+(input.creditedAdditionalMonths||0);
        if(input.continueContributing&&compare(date,input.asOfDate)>0)total+=completeMonthsBetween(input.asOfDate,date);
        return total;
    }
    function validateCommon(input) {
        if(!input||typeof input!=="object"||Array.isArray(input))return invalid("input","OBJECT_REQUIRED");
        if(input.regime!==undefined&&input.regime!==REGIME.GENERAL_STANDARD)return {status:STATUS.OUT_OF_SCOPE,reason:"SPECIAL_REGIME_NOT_SUPPORTED"};
        const birth=parseDate(input.birthDate),asOf=parseDate(input.asOfDate);
        if(!birth)return invalid("birthDate","INVALID_ISO_DATE"); if(!asOf)return invalid("asOfDate","INVALID_ISO_DATE"); if(compare(input.birthDate,input.asOfDate)>0)return invalid("birthDate","FUTURE_BIRTH_DATE");
        if(!integer(input.contributedMonthsAsOfDate)||input.contributedMonthsAsOfDate<0)return invalid("contributedMonthsAsOfDate","NON_NEGATIVE_INTEGER_REQUIRED");
        if(typeof input.continueContributing!=="boolean")return invalid("continueContributing","BOOLEAN_REQUIRED");
        if(input.creditedAdditionalMonths!==undefined&&(!integer(input.creditedAdditionalMonths)||input.creditedAdditionalMonths<0))return invalid("creditedAdditionalMonths","NON_NEGATIVE_INTEGER_REQUIRED");
        if(input.specificCarenceMonths!==undefined&&(!integer(input.specificCarenceMonths)||input.specificCarenceMonths<0))return invalid("specificCarenceMonths","NON_NEGATIVE_INTEGER_REQUIRED");
        for(const field of ["specificCarenceMet","qualifyingTerminationConfirmed","employmentRegistrationRequirementMet","additionalLegalRequirementsConfirmed"]){if(input[field]!==undefined&&typeof input[field]!=="boolean")return invalid(field,"BOOLEAN_REQUIRED");}
        if(input.specificCarenceMonths!==undefined&&input.specificCarenceMet!==undefined&&(input.specificCarenceMonths>=N.specificCarence.monthsRequired)!==input.specificCarenceMet)return invalid("specificCarenceMet","CONFLICTING_SPECIFIC_CARENCE_DATA");
        if(input.specialSituation!==undefined&&input.specialSituation!=="NONE")return {status:STATUS.OUT_OF_SCOPE,reason:"SPECIAL_SITUATION_NOT_SUPPORTED"};
        return null;
    }
    function calculateOrdinaryRetirement(input) {
        const error=validateCommon(input); if(error)return error;
        const birthYear=parseDate(input.birthDate).getUTCFullYear(), candidates=[],minimumAgeMonths=N.minimumOrdinaryAge.years*12+N.minimumOrdinaryAge.months,maximumAgeMonths=N.ordinaryAgeCalendar.reduce(function(max,r){return Math.max(max,r.ordinaryAge.years*12+r.ordinaryAge.months);},minimumAgeMonths);
        const age65=addMonths(input.birthDate,minimumAgeMonths), currentRule=ruleForYear(parseDate(input.asOfDate).getUTCFullYear());
        if(compare(input.asOfDate,age65)>0&&currentRule&&projectedMonths(input,input.asOfDate)>=currentRule.thresholdMonths)return {status:STATUS.REQUIRES_SPECIAL_ANALYSIS,reason:"HISTORICAL_THRESHOLD_DATE_REQUIRES_CONTRIBUTION_HISTORY"};
        for(let year=birthYear+N.minimumOrdinaryAge.years;year<=birthYear+Math.ceil(maximumAgeMonths/12)+1;year+=1){const rule=ruleForYear(year);if(!rule)continue;const high=addMonths(input.birthDate,rule.ordinaryAge.years*12+rule.ordinaryAge.months);if(parseDate(high).getUTCFullYear()===year)candidates.push({date:high,age:rule.ordinaryAge,requiresThreshold:false,rule:rule});}
        const scanStart=compare(input.asOfDate,age65)>0?input.asOfDate:age65;
        for(let offset=0;offset<=maximumAgeMonths-minimumAgeMonths;offset+=1){const date=addMonths(scanStart,offset),rule=ruleForYear(parseDate(date).getUTCFullYear());if(rule&&projectedMonths(input,date)>=rule.thresholdMonths)candidates.push({date:date,age:ageOn(input.birthDate,date),requiresThreshold:true,rule:rule});}
        candidates.sort(function(a,b){return compare(a.date,b.date);});
        let selected=null; for(let i=0;i<candidates.length;i+=1){const x=candidates[i],months=projectedMonths(input,x.date);if((x.requiresThreshold&&months>=x.rule.thresholdMonths)||!x.requiresThreshold){selected={date:x.date,age:x.age,contributedMonthsAtRetirement:months,thresholdMonths:x.rule.thresholdMonths,qualifiedForReducedOrdinaryAge:x.requiresThreshold};break;}}
        if(!selected)return {status:STATUS.REQUIRES_SPECIAL_ANALYSIS,reason:"ORDINARY_DATE_NOT_RESOLVED"};
        const totalMet=selected.contributedMonthsAtRetirement>=N.minimumContributionMonths.ordinary, specific=input.specificCarenceMonths!==undefined?input.specificCarenceMonths>=N.specificCarence.monthsRequired:input.specificCarenceMet;
        let eligibilityStatus=totalMet?(specific===true?STATUS.OK:specific===false?STATUS.NOT_ELIGIBLE:STATUS.SPECIFIC_CARENCE_UNKNOWN):STATUS.MINIMUM_CONTRIBUTION_NOT_MET;
        const warnings=input.continueContributing?[WARNING.PROJECTED_CONTINUED_CONTRIBUTIONS]:[];if(specific===undefined)warnings.push(WARNING.SPECIFIC_CARENCE_NOT_CONFIRMED);
        return {status:STATUS.OK,ordinary:selected,carence:{totalStatus:totalMet?"TOTAL_CARENCE_MET":"TOTAL_CARENCE_NOT_MET",specificStatus:specific===true?"SPECIFIC_CARENCE_MET":specific===false?"SPECIFIC_CARENCE_NOT_MET":"SPECIFIC_CARENCE_UNKNOWN",eligibilityStatus:eligibilityStatus},warnings:warnings};
    }
    function percentageRule(year){return N.percentageScales.find(function(r){return year>=r.fromYear&&(r.toYear===null||year<=r.toYear);});}
    function calculatePensionPercentage(input){
        if(!input||!integer(input.contributedMonths)||input.contributedMonths<0)return invalid("contributedMonths","NON_NEGATIVE_INTEGER_REQUIRED");
        if(!integer(input.eventYear)||!percentageRule(input.eventYear))return invalid("eventYear","UNSUPPORTED_YEAR");
        const rule=percentageRule(input.eventYear); if(input.contributedMonths<rule.baseMonths)return {status:STATUS.MINIMUM_CONTRIBUTION_NOT_MET,rate:0};
        let remaining=input.contributedMonths-rule.baseMonths,units=500000; rule.steps.forEach(function(s){const used=Math.min(remaining,s.months);units+=Math.round(s.rate*1000000)*used;remaining-=used;});
        return {status:STATUS.OK,rate:Math.min(units,1000000)/1000000,percentage:Math.min(units,1000000)/10000,contributedMonths:input.contributedMonths};
    }
    function bandIndex(months){return N.coefficientBands.findIndex(function(b){return months>=b.min&&(b.max===null||months<=b.max);});}
    function coefficient(mode,monthsEarly,contributedMonths){const def=mode==="VOLUNTARY"?N.voluntaryEarly:N.involuntaryEarly;if(!integer(monthsEarly)||monthsEarly<1||monthsEarly>def.maxMonths)return null;const row=def.table.find(function(x){return x.monthsEarly===monthsEarly;});return row.rates[bandIndex(contributedMonths)];}
    function calculateEarlyRetirementMonths(ordinaryDate,proposedDate){if(!parseDate(ordinaryDate)||!parseDate(proposedDate)||compare(proposedDate,ordinaryDate)>0)return null;if(proposedDate===ordinaryDate)return 0;let n=completeMonthsBetween(proposedDate,ordinaryDate);if(compare(addMonths(proposedDate,n),ordinaryDate)<0)n+=1;return n;}
    function referenceOrdinaryAtProposed(input,proposedDate,actualMonths){return calculateOrdinaryRetirement({birthDate:input.birthDate,asOfDate:proposedDate,contributedMonthsAsOfDate:actualMonths,continueContributing:true,specificCarenceMet:input.specificCarenceMet,creditedAdditionalMonths:0});}
    function calculateEarly(input,mode){
        const error=validateCommon(input);if(error)return error;if(!parseDate(input.proposedRetirementDate))return invalid("proposedRetirementDate","INVALID_ISO_DATE");
        const specific=input.specificCarenceMonths!==undefined?input.specificCarenceMonths>=N.specificCarence.monthsRequired:input.specificCarenceMet;
        if(specific===false)return {status:STATUS.NOT_ELIGIBLE,mode:mode,reason:"SPECIFIC_CARENCE_NOT_MET"};
        const actual=projectedMonths(input,input.proposedRetirementDate),reference=referenceOrdinaryAtProposed(input,input.proposedRetirementDate,actual);if(reference.status!==STATUS.OK)return reference;
        const early=calculateEarlyRetirementMonths(reference.ordinary.date,input.proposedRetirementDate),def=mode==="VOLUNTARY"?N.voluntaryEarly:N.involuntaryEarly,min=mode==="VOLUNTARY"?N.minimumContributionMonths.voluntary:N.minimumContributionMonths.involuntary;
        if(early===null||early<1||early>def.maxMonths||actual<min)return {status:STATUS.NOT_ELIGIBLE,mode:mode,monthsEarly:early,contributedMonthsAtProposedDate:actual,ordinaryReference:reference.ordinary};
        const warnings=[];let requirements;
        if(mode==="VOLUNTARY"){warnings.push(WARNING.PENSION_MINIMUM_NOT_EVALUATED);if(specific!==true)warnings.push(WARNING.SPECIFIC_CARENCE_NOT_CONFIRMED);requirements={ageAndContributionsMet:true,specificCarence:specific===true?"DECLARED_MET":"UNKNOWN",minimumPensionRequirement:"NOT_EVALUATED",fullLegalEligibilityConfirmed:false};}
        else {const cause=input.qualifyingTerminationConfirmed,registration=input.employmentRegistrationRequirementMet,additional=input.additionalLegalRequirementsConfirmed; if(cause!==true)warnings.push(WARNING.INVOLUNTARY_LEGAL_CAUSE_NOT_VERIFIED);requirements={ageAndContributionsMet:true,qualifyingTermination:cause===true?"DECLARED_MET":cause===false?"DECLARED_NOT_MET":"UNKNOWN",employmentRegistration:registration===true?"DECLARED_MET":registration===false?"DECLARED_NOT_MET":"UNKNOWN",additionalLegalRequirements:additional===true?"DECLARED_MET":additional===false?"DECLARED_NOT_MET":"UNKNOWN",specificCarence:specific===true?"DECLARED_MET":specific===false?"DECLARED_NOT_MET":"UNKNOWN",fullLegalEligibilityConfirmed:cause===true&&registration===true&&additional===true&&specific===true};}
        return {status:requirements.fullLegalEligibilityConfirmed?STATUS.OK:STATUS.POTENTIALLY_ELIGIBLE,mode:mode,proposedRetirementDate:input.proposedRetirementDate,ordinaryReference:reference.ordinary,monthsEarly:early,contributedMonthsAtProposedDate:actual,contributionMonthsForOrdinaryAgeReference:reference.ordinary.contributedMonthsAtRetirement,reductionRate:coefficient(mode,early,actual),requirements:requirements,warnings:warnings};
    }
    function calculateVoluntaryEarlyRetirement(input){return calculateEarly(input,"VOLUNTARY");}
    function calculateInvoluntaryEarlyRetirement(input){return calculateEarly(input,"INVOLUNTARY");}
    function calculateEarlyRetirementScenario(input){if(!input||!integer(input.monthsEarly)||input.monthsEarly<0)return invalid("monthsEarly","NON_NEGATIVE_INTEGER_REQUIRED");if(input.mode!=="VOLUNTARY"&&input.mode!=="INVOLUNTARY")return invalid("mode","EARLY_MODE_REQUIRED");const mode=input.mode,max=mode==="INVOLUNTARY"?N.involuntaryEarly.maxMonths:N.voluntaryEarly.maxMonths;if(input.monthsEarly>max)return {status:STATUS.NOT_ELIGIBLE,reason:"MAXIMUM_EARLY_MONTHS_EXCEEDED",monthsEarly:input.monthsEarly};const ordinary=calculateOrdinaryRetirement(input);if(ordinary.status!==STATUS.OK)return ordinary;if(input.monthsEarly===0)return {status:STATUS.OK,mode:"ORDINARY",proposedRetirementDate:ordinary.ordinary.date,monthsEarly:0,reductionRate:0};for(let offset=input.monthsEarly;offset<=max+36;offset+=1){const proposed=addMonths(ordinary.ordinary.date,-offset),next=Object.assign({},input,{proposedRetirementDate:proposed}),result=mode==="INVOLUNTARY"?calculateInvoluntaryEarlyRetirement(next):calculateVoluntaryEarlyRetirement(next);if(result.monthsEarly===input.monthsEarly)return result;}return {status:STATUS.NOT_ELIGIBLE,mode:mode,reason:"EXACT_EARLY_SCENARIO_NOT_RESOLVED",monthsEarly:input.monthsEarly};}
    function calculateEarliestRetirement(input){const ordinary=calculateOrdinaryRetirement(input);if(ordinary.status!==STATUS.OK)return ordinary;const voluntary=calculateEarlyRetirementScenario(Object.assign({},input,{mode:"VOLUNTARY",monthsEarly:24}));const involuntary=calculateEarlyRetirementScenario(Object.assign({},input,{mode:"INVOLUNTARY",monthsEarly:48}));return {status:STATUS.OK,ordinary:ordinary,voluntaryEarly:voluntary,involuntaryEarlyPotential:involuntary};}
    function calculateRetirementPension(input){
        if(!input||!finiteNumber(input.baseRegulatory)||input.baseRegulatory<=0)return invalid("baseRegulatory","POSITIVE_FINITE_NUMBER_REQUIRED");
        const p=calculatePensionPercentage({contributedMonths:input.contributedMonths,eventYear:input.eventYear});if(p.status!==STATUS.OK)return p;
        const reduction=input.reductionRate===undefined?0:input.reductionRate;if(!finiteNumber(reduction)||reduction<0||reduction>=1)return invalid("reductionRate","RATE_OUT_OF_RANGE");
        const before=input.baseRegulatory*p.rate,after=before*(1-reduction),annual=after*N.pensionPaymentsPerYear;if(!Number.isFinite(before)||!Number.isFinite(after)||!Number.isFinite(annual)||before<=0||after<=0)return invalid("baseRegulatory","RESULT_NOT_FINITE_OR_UNDERFLOWED");
        return {status:STATUS.OK,baseRegulatory:input.baseRegulatory,percentageRate:p.rate,reductionRate:reduction,monthlyGrossBeforeReduction:before,monthlyGross:after,monthlyDifference:before-after,annualGross:annual,paymentsPerYear:N.pensionPaymentsPerYear,warnings:[WARNING.BASE_REGULATORY_PROVIDED_BY_USER,WARNING.PENSION_MAXIMUM_NOT_APPLIED,WARNING.PENSION_MINIMUM_NOT_EVALUATED]};
    }
    function calculateBaseRegulatory(input){if(!input||input.mode!=="CONTRIBUTION_BASE_HISTORY")return invalid("mode","CONTRIBUTION_BASE_HISTORY_REQUIRED");if(!Array.isArray(input.monthlyBases))return invalid("monthlyBases","ARRAY_REQUIRED");if(input.monthlyBases.some(function(x){return x===null||x===undefined;}))return {status:STATUS.REQUIRES_SPECIAL_ANALYSIS,reason:"CONTRIBUTION_GAPS_REQUIRE_LEGAL_INTEGRATION",warnings:[WARNING.ADVANCED_BASE_REQUIRES_IPC_AND_GAP_RULES]};return {status:STATUS.REQUIRES_SPECIAL_ANALYSIS,reason:"IPC_SERIES_REQUIRED",warnings:[WARNING.ADVANCED_BASE_REQUIRES_IPC_AND_GAP_RULES]};}
    function validateDeferred(input){
        if(!input||typeof input!=="object"||Array.isArray(input))return invalid("input","OBJECT_REQUIRED");
        if(!parseDate(input.ordinaryRetirementDate))return invalid("ordinaryRetirementDate","INVALID_ISO_DATE");if(!parseDate(input.deferredRetirementDate))return invalid("deferredRetirementDate","INVALID_ISO_DATE");
        if(compare(input.deferredRetirementDate,input.ordinaryRetirementDate)<0)return invalid("deferredRetirementDate","DATE_BEFORE_ORDINARY_RETIREMENT");
        if(!integer(input.effectiveContributionMonthsDuringDeferral)||input.effectiveContributionMonthsDuringDeferral<0)return invalid("effectiveContributionMonthsDuringDeferral","NON_NEGATIVE_INTEGER_REQUIRED");
        const civil=completeMonthsBetween(input.ordinaryRetirementDate,input.deferredRetirementDate);if(input.effectiveContributionMonthsDuringDeferral>civil)return invalid("effectiveContributionMonthsDuringDeferral","EXCEEDS_CIVIL_MONTHS");
        for(const field of ["ordinaryCarenceMet","partialOrFlexibleRetirement","accessFromAssimilatedStatus","pensionAlreadyCaused"]){if(input[field]!==undefined&&typeof input[field]!=="boolean")return invalid(field,"BOOLEAN_REQUIRED");}
        return null;
    }
    function deferredPeriod(input){const months=input.effectiveContributionMonthsDuringDeferral;return {civilCompleteMonths:completeMonthsBetween(input.ordinaryRetirementDate,input.deferredRetirementDate),effectiveContributionMonths:months,fullYears:Math.floor(months/12),remainingMonths:months%12};}
    function deferredFractionApplies(input,period){return compare(input.deferredRetirementDate,N.deferredRetirement.statutoryEnhancementEffectiveDate)>=0&&period.fullYears>=2&&period.remainingMonths>N.deferredRetirement.additionalFractionMinimumMonthsExclusive;}
    function deferredEligibility(input,period){if(input.partialOrFlexibleRetirement===true||input.accessFromAssimilatedStatus===true||input.pensionAlreadyCaused===true)return {status:STATUS.OUT_OF_SCOPE,reason:input.pensionAlreadyCaused===true?"PENSION_ALREADY_CAUSED_IS_NOT_DEFERRAL":"INCOMPATIBLE_RETIREMENT_SITUATION"};if(input.ordinaryCarenceMet===false)return {status:STATUS.NOT_ELIGIBLE,reason:"ORDINARY_CARENCE_NOT_MET"};if(period.fullYears<1)return {status:STATUS.NOT_ELIGIBLE,reason:"NO_FULL_YEAR_OF_EFFECTIVE_DEFERRAL"};return {status:input.ordinaryCarenceMet===true?STATUS.OK:STATUS.POTENTIALLY_ELIGIBLE,reason:input.ordinaryCarenceMet===true?null:"ORDINARY_CARENCE_NOT_CONFIRMED"};}
    function deferredPensionProjection(input,rate){
        if(input.baseRegulatory===undefined||input.ordinaryPercentageRate===undefined||input.pensionMaximumAnnual===undefined)return {status:STATUS.REQUIRES_SPECIAL_ANALYSIS,reason:"BASE_PERCENTAGE_AND_MAXIMUM_PENSION_REQUIRED"};
        if(!finiteNumber(input.baseRegulatory)||input.baseRegulatory<=0)return invalid("baseRegulatory","POSITIVE_FINITE_NUMBER_REQUIRED");if(!finiteNumber(input.ordinaryPercentageRate)||input.ordinaryPercentageRate<=0||input.ordinaryPercentageRate>1)return invalid("ordinaryPercentageRate","RATE_OUT_OF_RANGE");if(!finiteNumber(input.pensionMaximumAnnual)||input.pensionMaximumAnnual<=0)return invalid("pensionMaximumAnnual","POSITIVE_FINITE_NUMBER_REQUIRED");
        const before=input.baseRegulatory*input.ordinaryPercentageRate,after=input.baseRegulatory*(input.ordinaryPercentageRate+rate),difference=after-before,annual=after*N.pensionPaymentsPerYear;if(!Number.isFinite(before)||!Number.isFinite(after)||!Number.isFinite(difference)||!Number.isFinite(annual)||before<=0)return invalid("baseRegulatory","RESULT_NOT_FINITE_OR_UNDERFLOWED");if(annual>input.pensionMaximumAnnual)return {status:STATUS.REQUIRES_SPECIAL_ANALYSIS,reason:"MAXIMUM_PENSION_AND_EXCESS_RULES_APPLY",uncappedAnnualGrossAfterBonus:annual};return {status:STATUS.OK,monthlyGrossBeforeBonus:before,monthlyGrossAfterBonus:after,monthlyDifference:difference,annualGrossAfterBonus:annual,paymentsPerYear:N.pensionPaymentsPerYear};
    }
    function calculateDeferredPercentageBonus(input){
        const error=validateDeferred(input);if(error)return error;const p=deferredPeriod(input),eligibility=deferredEligibility(input,p);if(eligibility.status!==STATUS.OK&&eligibility.status!==STATUS.POTENTIALLY_ELIGIBLE)return Object.assign(eligibility,{period:p});
        const d=N.deferredRetirement,half=deferredFractionApplies(input,p),rate=p.fullYears*d.annualPercentageRate+(half?d.additionalFractionRate:0),result={status:eligibility.status,option:DEFERRED_OPTION.PERCENTAGE,period:p,additionalPercentageRate:rate,additionalPercentage:rate*100,fractionRecognized:half};result.pension=deferredPensionProjection(input,rate);if(result.pension.status===STATUS.INVALID_INPUT)return result.pension;return result;
    }
    function lumpUnit(input){const d=N.deferredRetirement.lumpSum,annual=Math.min(input.initialAnnualPension,input.pensionMaximumAnnual),factor=input.contributedMonthsAtOrdinaryDate>=d.longCareerThresholdMonths?d.longCareerMultiplier:1,value=d.baseFactor*Math.pow(annual/d.annualPensionDivisor,1/d.exponentDenominator)*factor;return Number.isFinite(value)&&value>0?value:null;}
    function validateLumpData(input){for(const field of ["initialAnnualPension","pensionMaximumAnnual"]){if(!finiteNumber(input[field])||input[field]<=0)return invalid(field,"POSITIVE_FINITE_NUMBER_REQUIRED");}if(!integer(input.contributedMonthsAtOrdinaryDate)||input.contributedMonthsAtOrdinaryDate<0)return invalid("contributedMonthsAtOrdinaryDate","NON_NEGATIVE_INTEGER_REQUIRED");if(input.multiplePensionsConfirmed!==false)return {status:STATUS.REQUIRES_SPECIAL_ANALYSIS,reason:"PENSION_CONCURRENCE_NOT_EXCLUDED"};if(input.internationalProration!==false)return {status:STATUS.OUT_OF_SCOPE,reason:"INTERNATIONAL_PRORATION_NOT_SUPPORTED"};return null;}
    function calculateDeferredLumpSum(input){
        const error=validateDeferred(input);if(error)return error;const p=deferredPeriod(input),eligibility=deferredEligibility(input,p);if(eligibility.status!==STATUS.OK&&eligibility.status!==STATUS.POTENTIALLY_ELIGIBLE)return Object.assign(eligibility,{period:p});const data=validateLumpData(input);if(data)return data;const unit=lumpUnit(input);if(unit===null)return invalid("initialAnnualPension","RESULT_NOT_FINITE_OR_UNDERFLOWED");const d=N.deferredRetirement,half=deferredFractionApplies(input,p),units=p.fullYears+(half?d.lumpSum.fractionMultiplier:0),amount=unit*units;if(!Number.isFinite(amount))return invalid("initialAnnualPension","RESULT_NOT_FINITE");return {status:eligibility.status,option:DEFERRED_OPTION.LUMP_SUM,period:p,lumpSumUnit:unit,lumpSumUnits:units,fractionRecognized:half,lumpSumAmount:amount,pensionMonthlyGross:input.initialAnnualPension/N.pensionPaymentsPerYear};
    }
    function calculateDeferredMixedOption(input){
        const error=validateDeferred(input);if(error)return error;const p=deferredPeriod(input),eligibility=deferredEligibility(input,p);if(eligibility.status!==STATUS.OK&&eligibility.status!==STATUS.POTENTIALLY_ELIGIBLE)return Object.assign(eligibility,{period:p});if(compare(input.deferredRetirementDate,N.deferredRetirement.mixedOptionEffectiveDate)<0)return {status:STATUS.NOT_ELIGIBLE,reason:"MIXED_OPTION_NOT_YET_IN_FORCE",period:p};if(p.fullYears<N.deferredRetirement.mixedBeforeReform.minimumYears)return {status:STATUS.NOT_ELIGIBLE,reason:"MIXED_OPTION_REQUIRES_TWO_FULL_YEARS",period:p};if(compare(input.deferredRetirementDate,N.deferredRetirement.mixedAdaptationPendingFrom)>=0&&compare(input.deferredRetirementDate,N.deferredRetirement.mixedReformEffectiveDate)<0&&p.fullYears>=2&&p.remainingMonths>=6)return {status:STATUS.REQUIRES_SPECIAL_ANALYSIS,reason:"MIXED_SEMESTER_PENDING_REGULATORY_ADAPTATION",period:p};const data=validateLumpData(input);if(data)return data;
        const after=compare(input.deferredRetirementDate,N.deferredRetirement.mixedReformEffectiveDate)>=0,d=after?N.deferredRetirement.mixedAfterReform:N.deferredRetirement.mixedBeforeReform;let percentageYears,lumpYears,lumpHalf=false,percentageHalf=false;
        if(p.fullYears>=d.fixedLumpYearsFrom){lumpYears=d.fixedLumpYears;percentageYears=p.fullYears-lumpYears;if(after&&p.remainingMonths>=d.semesterMonths)percentageHalf=true;}else{percentageYears=Math.floor(p.fullYears/2);lumpYears=p.fullYears-percentageYears;if(after&&p.remainingMonths>=d.semesterMonths)lumpHalf=true;}
        const unit=lumpUnit(input);if(unit===null)return invalid("initialAnnualPension","RESULT_NOT_FINITE_OR_UNDERFLOWED");const rate=percentageYears*N.deferredRetirement.annualPercentageRate+(percentageHalf?N.deferredRetirement.additionalFractionRate:0),units=lumpYears+(lumpHalf?N.deferredRetirement.lumpSum.fractionMultiplier:0),amount=unit*units;if(!Number.isFinite(amount))return invalid("initialAnnualPension","RESULT_NOT_FINITE");const pension=deferredPensionProjection(input,rate);if(pension.status===STATUS.INVALID_INPUT)return pension;return {status:eligibility.status,option:DEFERRED_OPTION.MIXED,legalRegime:after?"RD_416_2026":"RD_371_2023_ORIGINAL",period:p,percentageYears:percentageYears,lumpSumYears:lumpYears,percentageSemesterRecognized:percentageHalf,lumpSumSemesterRecognized:lumpHalf,additionalPercentageRate:rate,lumpSumUnit:unit,lumpSumUnits:units,lumpSumAmount:amount,pension:pension};
    }
    function calculateDeferredRetirement(input){if(!input||!Object.values(DEFERRED_OPTION).includes(input.option))return invalid("option","DEFERRED_OPTION_REQUIRED");if(input.option===DEFERRED_OPTION.PERCENTAGE)return calculateDeferredPercentageBonus(input);if(input.option===DEFERRED_OPTION.LUMP_SUM)return calculateDeferredLumpSum(input);return calculateDeferredMixedOption(input);}
    function compareRetirementTiming(input){if(!input||typeof input!=="object"||Array.isArray(input))return invalid("input","OBJECT_REQUIRED");const ordinary=input.ordinary||null,early=input.early||null,deferred=input.deferred?calculateDeferredRetirement(input.deferred):null;return {status:STATUS.OK,ordinary:ordinary,early:early,deferred:deferred,recommendation:null};}
    function calculateRetirement(input){const ordinary=calculateOrdinaryRetirement(input);if(ordinary.status!==STATUS.OK)return ordinary;const percentage=calculatePensionPercentage({contributedMonths:ordinary.ordinary.contributedMonthsAtRetirement,eventYear:parseDate(ordinary.ordinary.date).getUTCFullYear()});const earliest=calculateEarliestRetirement(input);let pension=null;if(input.baseRegulatory!==undefined)pension=ordinary.carence.eligibilityStatus===STATUS.NOT_ELIGIBLE?{status:STATUS.NOT_ELIGIBLE,reason:"SPECIFIC_CARENCE_NOT_MET"}:calculateRetirementPension({baseRegulatory:input.baseRegulatory,contributedMonths:ordinary.ordinary.contributedMonthsAtRetirement,eventYear:parseDate(ordinary.ordinary.date).getUTCFullYear()});return {status:STATUS.OK,ordinary:ordinary,percentage:percentage,voluntaryEarly:earliest.voluntaryEarly,involuntaryEarlyPotential:earliest.involuntaryEarlyPotential,pension:pension,warnings:ordinary.warnings.slice()};}
    root.ImoancyJubilacionCore=Object.freeze({NORMATIVA:N,STATUS:STATUS,WARNING:WARNING,REGIME:REGIME,DEFERRED_OPTION:DEFERRED_OPTION,parseDate:parseDate,addMonths:addMonths,addYears:addYears,completeMonthsBetween:completeMonthsBetween,ageOn:ageOn,calculateOrdinaryRetirement:calculateOrdinaryRetirement,calculatePensionPercentage:calculatePensionPercentage,calculateEarlyRetirementMonths:calculateEarlyRetirementMonths,calculateVoluntaryEarlyRetirement:calculateVoluntaryEarlyRetirement,calculateInvoluntaryEarlyRetirement:calculateInvoluntaryEarlyRetirement,calculateEarlyRetirementScenario:calculateEarlyRetirementScenario,calculateEarliestRetirement:calculateEarliestRetirement,calculateRetirementPension:calculateRetirementPension,calculateBaseRegulatory:calculateBaseRegulatory,calculateDeferredPercentageBonus:calculateDeferredPercentageBonus,calculateDeferredLumpSum:calculateDeferredLumpSum,calculateDeferredMixedOption:calculateDeferredMixedOption,calculateDeferredRetirement:calculateDeferredRetirement,compareRetirementTiming:compareRetirementTiming,calculateRetirement:calculateRetirement});
}(typeof globalThis!=="undefined"?globalThis:this));
