"use strict";
const pruebas=[];const test=(n,f)=>pruebas.push([n,f]);const ok=(v,m)=>{if(!v)throw Error(m||"condición falsa")};const igual=(a,b)=>ok(Object.is(a,b),`${a} !== ${b}`);const cerca=(a,b,t=1e-8)=>ok(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),`${a} != ${b}`);
document.getElementById("app").addEventListener("load",()=>setTimeout(()=>{
 const frame=document.getElementById("app"),w=frame.contentWindow,d=frame.contentDocument,e=w.InteresCompuestoEngine,$=id=>d.getElementById(id),set=(id,v)=>{$(id).value=v},submit=()=>$("formulario-calculadora").dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));
 const base=(x={})=>Object.assign({capitalInicial:10000,aportacionPeriodica:0,plazoAnos:10,rentabilidadAnual:0,frecuenciaAportacion:"mensual",frecuenciaCapitalizacion:"mensual",momentoAportacion:"final"},x);
 test("A fórmula cerrada sin aportaciones",()=>cerca(e.simular(base({rentabilidadAnual:.05})).capitalFinal,10000*1.05**10));
 test("B anualidad mensual independiente",()=>{const m=1.05**(1/12)-1,esperado=10000*1.05**20+300*((1+m)**240-1)/m;cerca(e.simular(base({aportacionPeriodica:300,rentabilidadAnual:.05,plazoAnos:20})).capitalFinal,esperado)});
 test("C tasa cero identidad contable",()=>{const r=e.simular(base({aportacionPeriodica:317,plazoAnos:20}));cerca(r.capitalFinal,r.capitalInicial+r.aportacionesAcumuladas)});
 [-.01,-.2,-.5,-.99].forEach(tasa=>test(`D tasa negativa ${tasa} finita y cerrada`,()=>{const r=e.simular(base({rentabilidadAnual:tasa,plazoAnos:1}));ok(Number.isFinite(r.capitalFinal));cerca(r.capitalFinal,10000*(1+tasa))}));
 test("E límite mínimo aceptado",()=>igual(e.simular(base({rentabilidadAnual:e.LIMITES.rentabilidadMinima,plazoAnos:1})).estado,e.STATUS.OK));
 test("E límite máximo aceptado",()=>igual(e.simular(base({rentabilidadAnual:e.LIMITES.rentabilidadMaxima,plazoAnos:1})).estado,e.STATUS.OK));
 test("E bajo mínimo rechazado",()=>igual(e.simular(base({rentabilidadAnual:e.LIMITES.rentabilidadMinima-.0001})).estado,e.STATUS.ENTRADA_INVALIDA));
 test("E sobre máximo rechazado",()=>igual(e.simular(base({rentabilidadAnual:e.LIMITES.rentabilidadMaxima+.0001})).estado,e.STATUS.ENTRADA_INVALIDA));
 [1/12,1,20,100].forEach(plazo=>test(`F plazo ${plazo} válido`,()=>igual(e.simular(base({capitalInicial:1,plazoAnos:plazo})).estado,e.STATUS.OK)));
 [100+1/12,0,-1,1.01,"20",NaN,Infinity].forEach((plazo,i)=>test(`F plazo inválido ${i}`,()=>igual(e.simular(base({plazoAnos:plazo})).estado,e.STATUS.ENTRADA_INVALIDA)));
 test("G capital inicial cero",()=>igual(e.simular(base({capitalInicial:0,aportacionPeriodica:100})).estado,e.STATUS.OK));
 test("G aportación cero",()=>igual(e.simular(base()).aportacionesAcumuladas,0));
 test("G ambos cero",()=>igual(e.simular(base({capitalInicial:0})).capitalFinal,0));
 test("G cantidades muy pequeñas finitas",()=>ok(Number.isFinite(e.simular(base({capitalInicial:1e-9,aportacionPeriodica:1e-9,plazoAnos:1,rentabilidadAnual:.05})).capitalFinal)));
 test("G límite de importes aceptado",()=>igual(e.simular(base({capitalInicial:e.LIMITES.maximoImporte,aportacionPeriodica:e.LIMITES.maximoImporte,plazoAnos:1})).estado,e.STATUS.OK));
 test("G importe sobre límite rechazado",()=>igual(e.simular(base({capitalInicial:e.LIMITES.maximoImporte+1})).estado,e.STATUS.ENTRADA_INVALIDA));
 test("G importe negativo rechazado",()=>igual(e.simular(base({aportacionPeriodica:-1})).estado,e.STATUS.ENTRADA_INVALIDA));
 test("H principio supera final",()=>{const a=e.simular(base({aportacionPeriodica:100,rentabilidadAnual:.05,momentoAportacion:"principio"})),b=e.simular(base({aportacionPeriodica:100,rentabilidadAnual:.05}));ok(a.capitalFinal>b.capitalFinal)});
 test("H principio igual a final con 0%",()=>cerca(e.simular(base({aportacionPeriodica:100,momentoAportacion:"principio"})).capitalFinal,e.simular(base({aportacionPeriodica:100})).capitalFinal));
 Object.entries(e.FRECUENCIAS).forEach(([f,meses])=>test(`I frecuencia ${f} cuenta aportaciones`,()=>{const r=e.simular(base({capitalInicial:0,aportacionPeriodica:100,plazoAnos:2,frecuenciaAportacion:f}));igual(r.aportacionesAcumuladas,100*24/meses)}));
 [0,.02,-.02].forEach(inf=>test(`J inflación ${inf} fórmula independiente`,()=>{const r=e.simular(base({rentabilidadAnual:.05,inflacionAnual:inf}));cerca(r.capitalReal,r.capitalFinal/(1+inf)**10)}));
 test("J inflación no cambia nominal",()=>cerca(e.simular(base({rentabilidadAnual:.05,inflacionAnual:.02})).capitalFinal,e.simular(base({rentabilidadAnual:.05})).capitalFinal));
 test("J límites inflación finitos",()=>{ok(Number.isFinite(e.simular(base({capitalInicial:1,inflacionAnual:e.LIMITES.inflacionMinima})).capitalReal));ok(Number.isFinite(e.simular(base({capitalInicial:1,inflacionAnual:e.LIMITES.inflacionMaxima})).capitalReal))});
 test("K costes cero neutros",()=>cerca(e.simular(base({rentabilidadAnual:.07,costesAnuales:0})).capitalFinal,e.simular(base({rentabilidadAnual:.07})).capitalFinal));
 test("K costes referencia y contrafactual",()=>{const r=e.simular(base({aportacionPeriodica:100,rentabilidadAnual:.07,costesAnuales:.01}));cerca(r.capitalSinCostes,36776.686698509184);cerca(r.capitalFinal,34004.04902953747);cerca(r.impactoCostes,r.capitalSinCostes-r.capitalFinal)});
 test("K interpretación pública de costes correcta",()=>ok(d.documentElement.textContent.includes("no significa simplemente «comisiones pagadas»")&&d.documentElement.textContent.includes("crecimiento potencial dejado de generar")));
 test("L interés simple independiente",()=>{const r=e.compararIntereses(base({rentabilidadAnual:.05}));cerca(r.capitalFinalSimple,10000*(1+.05*10));cerca(r.capitalFinalCompuesto,10000*1.05**10);cerca(r.diferenciaAbsoluta,10000*1.05**10-15000)});
 test("M duplicación logarítmica",()=>{const r=e.calcularDuplicacion(.05);cerca(r.tiempoExactoAnos,Math.log(2)/Math.log1p(.05));cerca(r.regla72Anos,14.4)});
 test("M duplicación cero/negativa no alcanzable",()=>{igual(e.calcularDuplicacion(0).estado,e.STATUS.DUPLICACION_NO_ALCANZABLE);igual(e.calcularDuplicacion(-.1).estado,e.STATUS.DUPLICACION_NO_ALCANZABLE)});
 test("N serie termina en resultado",()=>{const r=e.simular(base({aportacionPeriodica:123,rentabilidadAnual:.043,costesAnuales:.01}));cerca(r.serie.at(-1).capitalFinal,r.capitalFinal);cerca(r.serie.at(-1).aportadoAcumulado,r.dineroTotalAportado);cerca(r.dineroTotalAportado+r.rendimientoAcumulado,r.capitalFinal);cerca(r.resumenAnual.at(-1).capitalFinal,r.capitalFinal)});
 test("N serie es continua",()=>{const s=e.simular(base({aportacionPeriodica:123,rentabilidadAnual:.043})).serie;for(let i=1;i<s.length;i++)cerca(s[i].capitalInicial,s[i-1].capitalFinal)});
 test("N hitos coinciden con resumen",()=>{const r=e.simular(base({aportacionPeriodica:300,rentabilidadAnual:.05,plazoAnos:20}));r.hitos.capitalPorAno.forEach(h=>cerca(h.capital,r.resumenAnual[h.ano-1].capitalFinal))});
 test("UI válido genera todos los bloques",()=>{submit();["capital-final-titulo","grafico","comparacion-titulo","hitos-titulo","duplicacion-titulo","tabla-titulo"].forEach(id=>ok($(id),id))});
 ["","   ","texto","€","NaN","Infinity","1,5"].forEach((valor,i)=>test(`UI capital problemático ${i}`,()=>{set("capitalInicial",valor);submit();ok($("resultado").hidden);igual($("capitalInicial").getAttribute("aria-invalid"),"true");ok($("error-capital").textContent.length>0)}));
 test("UI -0 válido",()=>{set("capitalInicial","-0");submit();ok(!$("resultado").hidden)});
 test("UI punto decimal válido",()=>{set("capitalInicial","1.5");submit();ok(!$("resultado").hidden)});
 test("UI notación científica válida",()=>{set("capitalInicial","1e4");submit();ok(!$("resultado").hidden)});
 test("UI enorme rechazado y borra resultado anterior",()=>{set("capitalInicial","1e20");submit();ok($("resultado").hidden);ok(!$("grafico")&&!$("comparacion-titulo")&&!$("hitos-titulo")&&!$("tabla-titulo"))});
 test("UI errores de los seis campos asociados",()=>{const casos=[["capitalInicial","-1","error-capital"],["aportacionMensual","-1","error-aportacion"],["anos","0","error-plazo"],["rentabilidadAnual","1001","error-rentabilidad"]];casos.forEach(([id,v,err])=>{w.reiniciar();set(id,v);submit();igual($(id).getAttribute("aria-invalid"),"true");ok($(err).textContent.length>0);ok($(id).getAttribute("aria-describedby").includes(err))})});
 test("UI inflación sola",()=>{w.reiniciar();$("activarInflacion").click();submit();ok($("inflacion-titulo")&&!$("costes-titulo"))});
 test("UI costes solos",()=>{w.reiniciar();$("activarCostes").click();submit();ok($("costes-titulo")&&!$("inflacion-titulo"))});
 test("UI inflación y costes",()=>{w.reiniciar();$("activarInflacion").click();$("activarCostes").click();submit();ok($("costes-titulo")&&$("inflacion-titulo"))});
 test("UI negativo con inflación y costes",()=>{set("rentabilidadAnual","-20");submit();ok(!$("resultado").hidden&&!/NaN|Infinity/.test($("resultado").textContent))});
 test("UI error inflación accesible",()=>{set("rentabilidadAnual","5");set("inflacionAnual","1001");submit();igual($("inflacionAnual").getAttribute("aria-invalid"),"true");ok($("error-inflacion").textContent.length>0)});
 test("UI error costes accesible",()=>{set("inflacionAnual","2");set("costesAnuales","100");submit();igual($("costesAnuales").getAttribute("aria-invalid"),"true");ok($("error-costes").textContent.length>0)});
 test("Limpiar complejo restaura todo",()=>{w.reiniciar();$("opciones-avanzadas").open=true;$("frecuenciaAportacion").value="trimestral";$("momentoAportacion").value="principio";$("activarInflacion").click();$("activarCostes").click();submit();$("boton-limpiar").click();igual($("capitalInicial").value,"10000");igual($("frecuenciaAportacion").value,"mensual");igual($("momentoAportacion").value,"final");ok(!$("opciones-avanzadas").open&&$("campo-inflacion").hidden&&$("campo-costes").hidden&&$("resultado").hidden&&!$("grafico"))});
 test("Gráfico recalculado destruye instancia",()=>{submit();const canvas1=$("grafico"),chart1=w.Chart.getChart(canvas1);set("anos","1");submit();const chart2=w.Chart.getChart($("grafico"));ok(chart1!==chart2&&!w.Chart.getChart(canvas1));igual(chart2.config.data.datasets.length,2);igual(chart2.config.data.labels.length,1)});
 test("Gráfico último punto coincide con capital mostrado del motor",()=>{const chart=w.Chart.getChart($("grafico")),r=e.simular(base({aportacionPeriodica:300,rentabilidadAnual:.05,plazoAnos:1}));cerca(chart.config.data.datasets[1].data.at(-1),r.capitalFinal)});
 test("Resumen 100 años conserva 100 filas",()=>{w.reiniciar();set("anos","100");submit();igual(d.querySelectorAll(".tabla-anual tbody tr").length,100)});
 [320,375,390,430,768,1024,1440].forEach(ancho=>test(`Escenario 100 años sin overflow a ${ancho}px`,()=>{frame.style.width=`${ancho}px`;void frame.offsetWidth;ok(d.documentElement.scrollWidth<=d.documentElement.clientWidth+1,`${d.documentElement.scrollWidth}/${d.documentElement.clientWidth}`)}));
 test("ARIA referencias existentes",()=>{d.querySelectorAll("[aria-describedby]").forEach(n=>n.getAttribute("aria-describedby").split(/\s+/).forEach(id=>ok($(id),`${n.id}->${id}`)))});
 test("IDs únicos",()=>{const ids=[...d.querySelectorAll("[id]")].map(n=>n.id);igual(ids.length,new Set(ids).size)});
 test("controles con nombre accesible",()=>{d.querySelectorAll("input,select,button").forEach(n=>{if(n.type!=="checkbox"&&n.tagName!=="BUTTON")ok(d.querySelector(`label[for='${n.id}']`),n.id)})});
 let pass=0;const fallos=[];pruebas.forEach(([n,f])=>{try{f();pass++}catch(err){fallos.push(`${n}: ${err.message}`)}});document.getElementById("salida").textContent=`TOTAL: ${pruebas.length}\nSUPERADOS: ${pass}\nFALLIDOS: ${fallos.length}${fallos.length?`\n\n${fallos.join("\n")}`:""}`;
},1200));
