"use strict";
const pruebas=[];const test=(n,f)=>pruebas.push([n,f]);const ok=(v,m)=>{if(!v)throw Error(m||"condición falsa")};const igual=(a,b)=>ok(a===b,`${a} !== ${b}`);const cerca=(a,b,t=.01)=>ok(Math.abs(a-b)<=t,`${a} != ${b}`);const limpio=s=>s.replace(/\s+/g," ").trim();
document.getElementById("app").addEventListener("load",()=>setTimeout(()=>{
 const frame=document.getElementById("app"),w=frame.contentWindow,d=frame.contentDocument,$=s=>d.querySelector(s),$$=s=>[...d.querySelectorAll(s)];
 const schemas=$$('script[type="application/ld+json"]').map(n=>JSON.parse(n.textContent));const faqSchema=schemas.find(x=>x["@type"]==="FAQPage");const graph=schemas.find(x=>x["@graph"])["@graph"];
 test("title definitivo",()=>igual(d.title,"Calculadora de Interés Compuesto PRO | Imoancy"));
 test("title no supera 60 caracteres",()=>ok(d.title.length<=60,`${d.title.length}`));
 test("description útil",()=>ok($("meta[name='description']").content.includes("aportaciones periódicas")&&$("meta[name='description']").content.includes("inflación y costes")));
 test("description razonable",()=>ok($("meta[name='description']").content.length>=120&&$("meta[name='description']").content.length<=160,`${$("meta[name='description']").content.length}`));
 test("canonical exacto",()=>igual($("link[rel='canonical']").href,"https://imoancy.com/herramientas/calculadora-interes-compuesto-avanzada/"));
 test("iconos técnicos declarados",()=>{ok($("link[rel='icon'][href='icons/favicon.svg']"));ok($("link[rel='apple-touch-icon'][href='../../assets/brand/apple-touch-icon.png']"))});
 test("un único H1",()=>igual($$("h1").length,1));
 test("H1 definitivo",()=>igual(limpio($("h1").textContent),"Calculadora de Interés Compuesto PRO"));
 test("jerarquía headings sin saltos",()=>{let anterior=1;$$('h1,h2,h3,h4,h5,h6').forEach(h=>{const nivel=+h.tagName[1];ok(nivel<=anterior+1,`${h.textContent}: ${anterior}>${nivel}`);anterior=nivel})});
 test("Open Graph completo",()=>["og:type","og:locale","og:site_name","og:title","og:description","og:url","og:image","og:image:alt"].forEach(p=>ok($(`meta[property='${p}']`))));
 test("Open Graph actualizado",()=>igual($("meta[property='og:title']").content,d.title));
 test("Twitter completo",()=>["twitter:card","twitter:title","twitter:description","twitter:url","twitter:image"].forEach(p=>ok($(`meta[name='${p}']`))));
 test("Twitter actualizado",()=>igual($("meta[name='twitter:title']").content,d.title));
 test("todos los JSON-LD parsean",()=>igual(schemas.length,2));
 test("SoftwareApplication verdadero",()=>{const app=graph.find(x=>x["@type"]==="SoftwareApplication");ok(app&&app.isAccessibleForFree===true&&app.applicationCategory==="FinanceApplication")});
 test("WebPage presente",()=>ok(graph.some(x=>x["@type"]==="WebPage")));
 test("FAQPage con 18 preguntas",()=>igual(faqSchema.mainEntity.length,18));
 test("FAQ visible con 18 preguntas",()=>igual($$(".faq-lista details").length,18));
 test("FAQ visible coincide exactamente con schema",()=>{$$(".faq-lista details").forEach((n,i)=>{igual(limpio(n.querySelector("summary").textContent),faqSchema.mainEntity[i].name);igual(limpio(n.querySelector("p").textContent),faqSchema.mainEntity[i].acceptedAnswer.text)})});
 test("índice tiene destinos válidos",()=>{$$(".indice-guia a").forEach(a=>ok(d.getElementById(a.hash.slice(1)),a.hash))});
 test("todos los IDs son únicos",()=>{const ids=$$("[id]").map(n=>n.id);igual(new Set(ids).size,ids.length)});
 test("enlaces internos editoriales aprobados",()=>["calculadora-ahorro","calculadora-rentabilidad-inversiones","calculadora-inflacion","calculadora-fire"].forEach(slug=>ok($(`.contenido-editorial a[href*='/${slug}/']`),slug)));
 test("dos fuentes institucionales",()=>{igual($$(".contenido-editorial a[href^='https://www.bde.es'],.contenido-editorial a[href^='https://www.cnmv.es']").length,2)});
 test("enlaces externos protegidos",()=>$$('.contenido-editorial a[href^="https://www.bde.es"],.contenido-editorial a[href^="https://www.cnmv.es"]').forEach(a=>ok(a.rel.includes("noopener")&&a.rel.includes("noreferrer"))));
 test("fórmula de capital compuesto publicada",()=>ok(limpio($("#como-se-calcula").textContent).includes("CF = C₀ × (1 + r)t")));
 test("fórmula de tasa equivalente publicada",()=>ok(limpio($("#como-se-calcula").textContent).includes("tasaPeriodo = (1 + tasaAnual)1 / periodosPorAño − 1")));
 test("no afirma división anual entre doce",()=>ok($("#como-se-calcula").textContent.includes("no se divide simplemente entre doce")));
 test("fórmula de inflación publicada",()=>ok(limpio($("#inflacion-costes").textContent).includes("capitalReal = capitalNominal / (1 + inflación)años")));
 test("fórmula de duplicación publicada",()=>ok($("#duplicacion").textContent.includes("ln(2) / ln(1 + r)")));
 test("ejemplo A coincide con core",()=>{const r=w.InteresCompuestoEngine.simular({capitalInicial:10000,aportacionPeriodica:0,plazoAnos:10,rentabilidadAnual:.05});cerca(r.capitalFinal,16288.94626777452,1e-8);ok($("#ejemplos").textContent.includes("16.288,95 €"))});
 test("ejemplo A coincide con fórmula independiente",()=>cerca(10000*1.05**10,16288.94626777452,1e-8));
 test("ejemplo simple independiente",()=>cerca(10000*(1+.05*10),15000,1e-8));
 test("ejemplo B coincide con core",()=>{const r=w.InteresCompuestoEngine.simular({capitalInicial:10000,aportacionPeriodica:300,plazoAnos:20,rentabilidadAnual:.05,frecuenciaAportacion:"mensual",frecuenciaCapitalizacion:"mensual",momentoAportacion:"final"});cerca(r.capitalFinal,148274.3226467862,1e-8);cerca(r.rendimientoAcumulado,66274.3226467862,1e-8);igual(r.hitos.rendimientoSuperaAportaciones.ano,13)});
 test("ejemplo B coincide con anualidad independiente",()=>{const m=1.05**(1/12)-1;const esperado=10000*1.05**20+300*((1+m)**240-1)/m;cerca(esperado,148274.3226467862,1e-8)});
 test("metodología cubre supuestos",()=>["tasa anual efectiva hipotética","pasos mensuales","interés simple","inflación","costes","Regla del 72","precisión numérica","localmente"].forEach(x=>ok($("#metodologia").textContent.includes(x),x)));
 test("limitaciones explícitas",()=>["no está garantizada","impuestos","negativa","finalidad educativa"].forEach(x=>ok($("#limitaciones").textContent.includes(x),x)));
 test("privacidad editorial",()=>{const t=$("#sobre-calculadora").textContent;ok(t.includes("No requiere registro")&&t.includes("no se almacenan ni se envían"))});
 test("Herramientas relacionadas intactas",()=>{igual($$("#herramientas-relacionadas .imoancy-related__card").length,3);igual($$("#herramientas-relacionadas").length,1)});
 test("sin NaN o Infinity publicados",()=>ok(!/NaN|Infinity/.test(d.documentElement.textContent)));
 test("sin URLs github.io",()=>ok(!d.documentElement.innerHTML.includes("github.io")));
 test("GA4 exacto",()=>{igual($$("script[src*='googletagmanager.com/gtag/js?id=G-QH8MJ6LVHN']").length,1);ok($$("script:not([src])").some(s=>s.textContent.includes('gtag("config","G-QH8MJ6LVHN")')))});
 test("sin APIs o almacenamiento financiero",()=>{const js=$$('script:not([src])').map(s=>s.textContent).join(" ");ok(!/fetch\(|XMLHttpRequest|sendBeacon|localStorage|sessionStorage/.test(js))});
 [320,375,390,430,768,1024,1440].forEach(ancho=>test(`contenido sin overflow a ${ancho}px`,()=>{frame.style.width=`${ancho}px`;void frame.offsetWidth;ok(d.documentElement.scrollWidth<=d.documentElement.clientWidth+1,`${d.documentElement.scrollWidth}/${d.documentElement.clientWidth}`)}));
 let pass=0;const fallos=[];pruebas.forEach(([n,f])=>{try{f();pass++}catch(e){fallos.push(`${n}: ${e.message}`)}});document.getElementById("salida").textContent=`TOTAL: ${pruebas.length}\nSUPERADOS: ${pass}\nFALLIDOS: ${fallos.length}${fallos.length?`\n\n${fallos.join("\n")}`:""}`;
},900));
