"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const engine = require("../js/core.js");
const config = require("../js/config.js");
const { STATUS } = engine;
const cerca = (actual, esperado, tolerancia = 1e-8) => assert.ok(Math.abs(actual - esperado) <= tolerancia, `${actual} != ${esperado}`);

test("A: 12.000 en 12 meses requiere 1.000", () => cerca(engine.aportacionNecesaria({ objetivo: 12000, capitalInicial: 0, periodos: 12, rentabilidadAnual: 0 }).aportacionPeriodica, 1000));
test("B: 6.000 iniciales requieren 500", () => cerca(engine.aportacionNecesaria({ objetivo: 12000, capitalInicial: 6000, periodos: 12, rentabilidadAnual: 0 }).aportacionPeriodica, 500));
test("C: objetivo alcanzado", () => assert.equal(engine.aportacionNecesaria({ objetivo: 10000, capitalInicial: 10000, periodos: 12, rentabilidadAnual: 0 }).estado, STATUS.ALCANZADO));
test("D: objetivo superado", () => assert.equal(engine.aportacionNecesaria({ objetivo: 10000, capitalInicial: 12000, periodos: 12, rentabilidadAnual: 0 }).estado, STATUS.SUPERADO));
test("E: 1.000 al mes tarda 12 meses", () => assert.equal(engine.periodosNecesarios({ objetivo: 12000, capitalInicial: 0, aportacionPeriodica: 1000, rentabilidadAnual: 0 }).periodos, 12));
test("F: capacidad positiva", () => assert.deepEqual(engine.capacidadAhorro({ ingresosNetos: 2000, gastosFijos: 1000, gastosVariables: 400, otrosGastos: 100 }), { estado: STATUS.OK, gastosTotales: 1500, ahorroMensual: 500, porcentajeGastos: 0.75, tasaAhorro: 0.25, ahorroAnual: 6000 }));
test("G: déficit válido", () => { const r = engine.capacidadAhorro({ ingresosNetos: 2000, gastosFijos: 1200, gastosVariables: 1000 }); assert.equal(r.estado, STATUS.DEFICIT); cerca(r.ahorroMensual, -200); cerca(r.tasaAhorro, -0.1); });
test("H: inflación cero", () => cerca(engine.ajustarInflacion(10000, 0, 10).objetivoNominal, 10000));
test("I: fórmula positiva coincide con simulación independiente", () => { const d = { capitalInicial: 2500, aportacionPeriodica: 300, periodos: 240, rentabilidadAnual: 0.05 }; let capital = d.capitalInicial; const m = Math.pow(1.05, 1 / 12) - 1; for (let i = 0; i < d.periodos; i++) capital = capital * (1 + m) + d.aportacionPeriodica; cerca(engine.proyectarCapital(d).capitalFinal, capital, 1e-6); });
test("J: tasa cero es finita", () => assert.ok(Number.isFinite(engine.aportacionNecesaria({ objetivo: 1, capitalInicial: 0, periodos: 1, rentabilidadAnual: 0 }).aportacionPeriodica)));
test("K: rechaza no numérico", () => assert.equal(engine.aportacionNecesaria({ objetivo: "12000", capitalInicial: 0, periodos: 12, rentabilidadAnual: 0 }).estado, STATUS.INVALIDO));
test("K: rechaza periodos fraccionarios", () => assert.equal(engine.aportacionNecesaria({ objetivo: 12000, capitalInicial: 0, periodos: 1.5, rentabilidadAnual: 0 }).estado, STATUS.INVALIDO));
test("K: rechaza rentabilidad NaN", () => assert.equal(engine.aportacionNecesaria({ objetivo: 12000, capitalInicial: 0, periodos: 12, rentabilidadAnual: NaN }).estado, STATUS.INVALIDO));
test("L: horizonte largo finito", () => assert.ok(Number.isFinite(engine.proyectarCapital({ capitalInicial: 1, aportacionPeriodica: 1, periodos: 12000, rentabilidadAnual: 0.01 }).capitalFinal)));
test("M: aportación cero sin crecimiento es inalcanzable", () => assert.equal(engine.periodosNecesarios({ objetivo: 100, capitalInicial: 0, aportacionPeriodica: 0, rentabilidadAnual: 0 }).estado, STATUS.INALCANZABLE));
test("M: aportación cero con rendimiento puede alcanzar", () => assert.equal(engine.periodosNecesarios({ objetivo: 110, capitalInicial: 100, aportacionPeriodica: 0, rentabilidadAnual: 0.1 }).estado, STATUS.OK));
test("N: objetivo cero ya alcanzado", () => assert.equal(engine.aportacionNecesaria({ objetivo: 0, capitalInicial: 0, periodos: 0, rentabilidadAnual: 0 }).estado, STATUS.ALCANZADO));
test("O: capital inicial negativo rechazado", () => assert.equal(engine.aportacionNecesaria({ objetivo: 100, capitalInicial: -1, periodos: 12, rentabilidadAnual: 0 }).estado, STATUS.INVALIDO));
test("P: tasa positiva extrema razonable", () => assert.ok(Number.isFinite(engine.proyectarCapital({ capitalInicial: 100, aportacionPeriodica: 10, periodos: 120, rentabilidadAnual: 1 }).capitalFinal)));
test("P: tasa negativa superior a -100%", () => assert.ok(Number.isFinite(engine.proyectarCapital({ capitalInicial: 100, aportacionPeriodica: 10, periodos: 120, rentabilidadAnual: -0.5 }).capitalFinal)));
test("rechaza tasa de -100%", () => assert.equal(engine.proyectarCapital({ capitalInicial: 100, aportacionPeriodica: 10, periodos: 12, rentabilidadAnual: -1 }).estado, STATUS.INVALIDO));
test("periodos cero sin objetivo alcanzado", () => assert.equal(engine.aportacionNecesaria({ objetivo: 100, capitalInicial: 0, periodos: 0, rentabilidadAnual: 0 }).estado, STATUS.INALCANZABLE));
test("ingresos cero no genera Infinity", () => { const r = engine.capacidadAhorro({ ingresosNetos: 0, gastosFijos: 10, gastosVariables: 0 }); assert.equal(r.tasaAhorro, null); assert.equal(r.porcentajeGastos, null); });
test("campo opcional otros vacío/omitido vale cero", () => assert.equal(engine.capacidadAhorro({ ingresosNetos: 100, gastosFijos: 20, gastosVariables: 30 }).gastosTotales, 50));
test("inflación compuesta", () => cerca(engine.ajustarInflacion(10000, 0.02, 10).objetivoNominal, 10000 * Math.pow(1.02, 10)));
test("inflación negativa", () => assert.ok(engine.ajustarInflacion(10000, -0.02, 10).objetivoNominal < 10000));
test("métricas usan 12/52/365", () => assert.deepEqual(engine.metricasDerivadas({ objetivo: 1000, capitalInicial: 250, ahorroMensual: 100 }), { restante: 750, progreso: 0.25, ahorroMensual: 100, equivalenteSemanal: 1200 / 52, equivalenteDiario: 1200 / 365, ahorroAnual: 1200 }));
test("escenarios usan configuración central", () => { const r = engine.generarEscenarios(100, config.escenarios); assert.deepEqual(r.escenarios.map(x => x.aportacionPeriodica), [80, 100, 120]); });
test("proyección detalla aportación al final", () => { const s = engine.generarProyeccion({ capitalInicial: 100, aportacionPeriodica: 10, periodos: 1, rentabilidadAnual: 0.12 }).serie[0]; cerca(s.rendimientoEstimado, 100 * engine.tasaMensualDesdeAnual(0.12)); cerca(s.capitalFinal, 100 + s.rendimientoEstimado + 10); });
test("fecha objetivo suma meses", () => { const r = engine.fechaObjetivo(new Date(2026, 7, 10), 18); assert.equal(r.fecha.getFullYear(), 2028); assert.equal(r.fecha.getMonth(), 1); });
test("invariante: más capital no aumenta aportación", () => { const a = engine.aportacionNecesaria({ objetivo: 50000, capitalInicial: 0, periodos: 60, rentabilidadAnual: 0.04 }).aportacionPeriodica; const b = engine.aportacionNecesaria({ objetivo: 50000, capitalInicial: 5000, periodos: 60, rentabilidadAnual: 0.04 }).aportacionPeriodica; assert.ok(b <= a); });
test("invariante: más plazo no aumenta aportación", () => { const a = engine.aportacionNecesaria({ objetivo: 50000, capitalInicial: 0, periodos: 60, rentabilidadAnual: 0.04 }).aportacionPeriodica; const b = engine.aportacionNecesaria({ objetivo: 50000, capitalInicial: 0, periodos: 120, rentabilidadAnual: 0.04 }).aportacionPeriodica; assert.ok(b <= a); });
test("invariante: más aportación no aumenta plazo", () => { const a = engine.periodosNecesarios({ objetivo: 50000, capitalInicial: 0, aportacionPeriodica: 500, rentabilidadAnual: 0.04 }).periodos; const b = engine.periodosNecesarios({ objetivo: 50000, capitalInicial: 0, aportacionPeriodica: 750, rentabilidadAnual: 0.04 }).periodos; assert.ok(b <= a); });
test("invariante: rentabilidad positiva no reduce capital", () => { const z = engine.proyectarCapital({ capitalInicial: 1000, aportacionPeriodica: 100, periodos: 120, rentabilidadAnual: 0 }).capitalFinal; const p = engine.proyectarCapital({ capitalInicial: 1000, aportacionPeriodica: 100, periodos: 120, rentabilidadAnual: 0.05 }).capitalFinal; assert.ok(p >= z); });
test("invariante: más inflación no reduce objetivo", () => { const a = engine.ajustarInflacion(10000, 0.02, 20).objetivoNominal; const b = engine.ajustarInflacion(10000, 0.04, 20).objetivoNominal; assert.ok(b >= a); });
test("proyección cuadra con fórmula cerrada", () => { const d = { capitalInicial: 1000, aportacionPeriodica: 75, periodos: 360, rentabilidadAnual: 0.07 }; cerca(engine.generarProyeccion(d).capitalFinal, engine.proyectarCapital(d).capitalFinal, 1e-5); });
