/** Fuente única para FAQ visible y FAQPage JSON-LD. Orden estable e IDs únicos. */
export const FAQ_CONTENT = Object.freeze([
  { id:"cantidad-recien-nacido", pregunta:"¿Cuánta leche necesita un recién nacido?", respuesta:"Durante los primeros días las tomas suelen ser pequeñas y frecuentes. La cantidad varía según la edad exacta, el peso, el tipo de alimentación y las señales del bebé; por eso la herramienta ofrece un intervalo y no una cifra obligatoria." },
  { id:"ml-por-kilo", pregunta:"¿Cuántos mililitros por kilo debe tomar un bebé?", respuesta:"Las referencias por peso se utilizan como orientación en determinadas edades y modalidades, especialmente con fórmula. No deben interpretarse como una cantidad que todos los bebés tengan que completar ni aplicarse sin contexto a prematuros o situaciones clínicas." },
  { id:"dia-toma-menos", pregunta:"¿Es habitual que un bebé tome menos algunos días?", respuesta:"El apetito puede cambiar entre tomas y de un día a otro. El descanso, el ritmo de crecimiento, el entorno y el estado general pueden influir; conviene valorar el patrón completo y consultar si el cambio preocupa o persiste." },
  { id:"come-suficiente", pregunta:"¿Cómo puedo saber si mi bebé está comiendo suficiente?", respuesta:"Una cifra aislada no basta. La evolución del crecimiento, el estado general, el patrón de alimentación y de pañales, y la valoración en los controles aportan una visión más útil. Ante dudas, consulta al profesional que realiza el seguimiento." },
  { id:"pecho-en-ml", pregunta:"¿La lactancia materna directa puede medirse en mililitros?", respuesta:"No de forma fiable con la edad, el peso y el número de tomas. La transferencia al pecho varía y esta calculadora evita inventar un volumen; en lactancia directa prioriza señales, bienestar y seguimiento del crecimiento." },
  { id:"extraida-igual-pecho", pregunta:"¿Una toma de leche extraída equivale a una toma directa al pecho?", respuesta:"No necesariamente. El volumen ofrecido mediante recipiente no describe automáticamente la transferencia ni el patrón de una toma directa al pecho, y lo ofrecido tampoco tiene que coincidir con lo finalmente ingerido." },
  { id:"lactancia-mixta", pregunta:"¿Cómo calcula la herramienta la lactancia mixta?", respuesta:"Ofrece, cuando procede, una referencia global prudente. No estima cuánto obtiene el bebé del pecho, no calcula una cantidad individual de complemento y no resta automáticamente una modalidad de la otra." },
  { id:"numero-tomas", pregunta:"¿Cuántas tomas al día son habituales?", respuesta:"La frecuencia cambia con la edad, la modalidad de alimentación y cada bebé. En los primeros meses suelen ser más frecuentes y después pueden espaciarse, pero las señales de hambre y saciedad siguen siendo importantes." },
  { id:"rango-no-cifra", pregunta:"¿Por qué la calculadora muestra un rango y no una cifra exacta?", respuesta:"Porque las necesidades y el apetito no son idénticos en todos los bebés ni permanecen constantes. Un intervalo comunica mejor la incertidumbre y evita una falsa precisión." },
  { id:"terminar-biberon", pregunta:"¿Debe el bebé terminar siempre el biberón?", respuesta:"No debe interpretarse el resultado como una obligación de terminarlo. La alimentación responsiva tiene en cuenta las pausas y señales de saciedad, sin forzar una cantidad concreta." },
  { id:"solidos-necesidades", pregunta:"¿Cambian las necesidades al empezar la alimentación complementaria?", respuesta:"A partir de alrededor de los seis meses comienzan a incorporarse otros alimentos, pero el cambio es gradual. La herramienta utiliza este dato como contexto y no reduce automáticamente la leche ni asume un patrón concreto." },
  { id:"cuando-solidos", pregunta:"¿Cuándo suele comenzar la alimentación complementaria?", respuesta:"Los organismos de referencia la sitúan generalmente alrededor de los seis meses, teniendo en cuenta la preparación del bebé y el consejo sanitario. No debe utilizarse esta calculadora para decidir individualmente el momento de inicio." },
  { id:"prematuro", pregunta:"¿Puedo usar la calculadora con un bebé prematuro?", respuesta:"Puedes introducir los datos para obtener un contexto general, pero la herramienta no calcula cantidades individualizadas. La edad corregida, la evolución y las indicaciones de pediatría o neonatología pueden ser determinantes." },
  { id:"peso-reciente", pregunta:"¿Qué peso debo introducir?", respuesta:"Utiliza el peso reciente obtenido de forma fiable. La herramienta no interpreta por sí sola la trayectoria de crecimiento y un valor aislado no sustituye los controles." },
  { id:"edad-dias-semanas", pregunta:"¿Es mejor introducir la edad en días, semanas o meses?", respuesta:"Utiliza la unidad que permita expresar la edad cumplida con mayor claridad. El motor la convierte internamente a días para seleccionar la etapa correspondiente." },
  { id:"mas-rango", pregunta:"¿Qué ocurre si mi bebé toma más que el rango mostrado?", respuesta:"Un dato puntual fuera del intervalo no permite sacar conclusiones. Comprueba que los datos sean correctos y comenta los patrones persistentes o cualquier preocupación con el profesional sanitario." },
  { id:"menos-rango", pregunta:"¿Qué ocurre si toma menos que el rango orientativo?", respuesta:"Valora el contexto completo y no una sola toma. Si el patrón persiste, cambia de forma marcada o se acompaña de señales que te preocupan, solicita valoración sanitaria." },
  { id:"formula-concentracion", pregunta:"¿Puedo cambiar la concentración de la fórmula según el resultado?", respuesta:"No. Prepara siempre la fórmula siguiendo exactamente las instrucciones del fabricante y las indicaciones sanitarias. La calculadora no recomienda añadir más o menos agua o polvo." },
  { id:"resultado-diagnostico", pregunta:"¿El informe puede detectar un problema de alimentación?", respuesta:"No. El informe ofrece orientación y explica limitaciones, pero no diagnostica, no examina al bebé y no sustituye la valoración pediátrica." },
  { id:"privacidad", pregunta:"¿Se guardan los datos de mi bebé?", respuesta:"El cálculo y el historial se gestionan únicamente en este dispositivo. El historial conserva un resumen de cada informe en el almacenamiento local del navegador y puedes borrar cualquier registro o vaciarlo por completo cuando quieras." }
].map(Object.freeze));
