(function(root,factory){var api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.PinchazosCore=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){"use strict";
var LABELS=Object.freeze({posicion:{cubierta:"Hacia la cubierta",llanta:"Hacia la llanta",valvula:"Junto a la válvula",desconocida:"No lo sé"},forma:{pequeno:"Un agujero pequeño",doble:"Dos agujeros próximos",corte:"Corte o raja",valvula:"Daño junto a la válvula",no_localizado:"No consigo encontrarlo"},repeticion:{si:"Sí",no:"No",desconocida:"No lo sé"},momento:{golpe:"Después de un golpe, bache o bordillo",circulando:"Circulando sin un golpe claro",reparacion:"Poco después de cambiar o reparar la cámara",lenta:"Lentamente durante horas o días"},revision:{ambos:"Cubierta y fondo de llanta",cubierta:"Solo la cubierta",llanta:"Solo la llanta / fondo de llanta",ninguno:"Ninguno",desconocida:"No lo sé"}});
var CAUSES={
 cubierta:{title:"Objeto o daño procedente de la cubierta",check:"Inspecciona visualmente y con cuidado el interior de la cubierta en la zona correspondiente. Un cristal, espina, alambre u otro objeto pequeño puede seguir incrustado.",action:"Retira de forma segura cualquier objeto localizado y comprueba que la cubierta no conserve daños antes de montar otra cámara."},
 pellizco:{title:"Pellizco de la cámara contra la llanta",check:"Revisa el estado de la cubierta y la llanta, y que la cámara estuviera bien asentada. Comprueba una presión adecuada para cubierta, llanta, peso, carga y uso, respetando los límites de los fabricantes.",action:"Monta la cámara sin pliegues ni zonas atrapadas y ajusta la presión conforme a los límites y recomendaciones aplicables a tu conjunto."},
 llanta:{title:"Zona de llanta o fondo de llanta",check:"Revisa la zona interior correspondiente: fondo o cinta de llanta, agujeros de radios, posibles bordes, irregularidades y estado general del aro.",action:"Corrige o haz revisar cualquier borde, desplazamiento o deterioro encontrado antes de colocar otra cámara."},
 valvula:{title:"Válvula, base o zona del agujero de válvula",check:"Examina la válvula, su base, la posición de la cámara y el agujero de válvula de la llanta.",action:"Si la base está desgarrada o el daño es importante, sustituye la cámara y revisa el montaje en vez de confiar automáticamente en un parche normal."},
 lenta:{title:"Pérdida lenta sin una perforación claramente localizada",check:"Revisa de forma ordenada la válvula, la cámara, el interior de la cubierta y el montaje para localizar una pérdida muy pequeña.",action:"Localiza la fuga y su zona antes de repetir la reparación; no des por hecho un pinchazo concreto sin encontrar evidencia."},
 estructural:{title:"Daño importante que requiere revisar la rueda",check:"Comprueba si el corte o la raja afecta a la cubierta, su carcasa, la llanta o la seguridad del montaje.",action:"No te limites a poner otro parche: revisa correctamente la rueda o llévala a un taller si existe daño estructural o dudas sobre el montaje."}
};
function score(input){var s={cubierta:0,pellizco:0,llanta:0,valvula:0,lenta:0,estructural:0};if(input.posicion==="cubierta"){s.cubierta+=4;s.pellizco+=1;}if(input.posicion==="llanta")s.llanta+=6;if(input.posicion==="valvula")s.valvula+=7;if(input.forma==="pequeno")s.cubierta+=3;if(input.forma==="doble")s.pellizco+=7;if(input.forma==="corte")s.estructural+=10;if(input.forma==="valvula")s.valvula+=8;if(input.forma==="no_localizado")s.lenta+=5;if(input.repeticion==="si"){s.cubierta+=2;s.llanta+=2;}if(input.momento==="golpe")s.pellizco+=6;if(input.momento==="circulando")s.cubierta+=1;if(input.momento==="reparacion"){s.cubierta+=2;s.llanta+=2;s.valvula+=1;}if(input.momento==="lenta"){s.lenta+=6;s.valvula+=1;}return s;}
function ranked(input){var scores=score(input);return Object.keys(scores).map(function(id){return{id:id,score:scores[id]};}).sort(function(a,b){return b.score-a.score;});}
function checkedCover(input){return input.revision==="cubierta"||input.revision==="ambos";}function checkedRim(input){return input.revision==="llanta"||input.revision==="ambos";}
function configure(input){var order=ranked(input),primary=order[0],cause=CAUSES[primary.id],check=cause.check,secondary=[];
if(primary.id==="cubierta"){check=(checkedCover(input)?"Como ya revisaste la cubierta, vuelve a inspeccionar especialmente":"Inspecciona visualmente y con cuidado")+" la zona que corresponde al agujero. Usa la válvula como referencia para relacionar la posición de la cámara con la cubierta"+(checkedCover(input)?" y, si no aparece nada, comprueba también la llanta y su fondo.":". No pases los dedos agresivamente si puede haber vidrio o metal.");}
if(primary.id==="llanta"&&checkedRim(input))check="Como ya revisaste la llanta o su fondo, vuelve a comprobar especialmente la zona correspondiente al agujero: cinta, agujeros de radios, bordes e irregularidades internas.";
order.slice(1).filter(function(x){return x.score>0;}).slice(0,1).forEach(function(x){secondary.push(CAUSES[x.id].title+": "+CAUSES[x.id].check);});
var safety=input.forma==="corte"?["Has indicado un corte o raja. Comprueba si afecta a la cubierta, la carcasa, la llanta o al montaje de la rueda. Si existe un daño que pueda comprometerla, no sigas utilizando la bicicleta hasta revisarla correctamente o llevarla a un taller."]:[];
var why=[];if(input.forma==="doble")why.push("Dos agujeros próximos encajan especialmente con una cámara pellizcada contra la llanta.");if(input.momento==="golpe")why.push("El golpe o bordillo aumenta la compatibilidad con un pellizco.");if(input.posicion==="llanta")why.push("La cara interior de la cámara dirige la revisión hacia el fondo de llanta y el aro.");if(input.posicion==="valvula"||input.forma==="valvula")why.push("La ubicación del daño concentra la revisión en la válvula y su zona de montaje.");if(input.forma==="no_localizado"&&input.momento==="lenta")why.push("Sin un agujero localizado y con pérdida lenta, conviene revisar por orden sin inventar una perforación concreta.");if(!why.length)why.push("La posición, forma y momento del daño hacen que esta causa sea la más compatible con tus respuestas.");
return{primaryId:primary.id,ranking:order,parts:[{id:"causa",title:"Lo que más encaja",text:cause.title},{id:"comprobar",title:"Qué comprobar primero",text:check},{id:"accion",title:"Qué hacer antes de montar otra cámara",text:cause.action},{id:"secundarias",title:"Qué más conviene revisar",text:secondary.length?secondary.join(" "):"No hay otra causa con suficiente evidencia para priorizarla ahora."}],why:why,safety:safety,input:Object.assign({},input)};}
function compare(previous,next){var oldResult=configure(previous),newResult=configure(next),oldMap={},newMap={};oldResult.parts.forEach(function(x){oldMap[x.id]=x;});newResult.parts.forEach(function(x){newMap[x.id]=x;});var ids=Object.keys(newMap),changed=ids.filter(function(id){return oldMap[id].text!==newMap[id].text;}).map(function(id){return newMap[id];}),oldSafety=oldResult.safety.join(" "),newSafety=newResult.safety.join(" ");if(oldSafety!==newSafety)changed.push({id:"seguridad",title:"Seguridad",text:newSafety||"La advertencia reforzada deja de aplicar, pero mantén la comprobación general de la rueda."});return{changed:changed,maintained:ids.filter(function(id){return oldMap[id].text===newMap[id].text;}).map(function(id){return newMap[id];}),result:newResult,priorityChanged:oldResult.primaryId!==newResult.primaryId};}
return{configure:configure,compare:compare,score:score,labels:LABELS};});
