(function(root,factory){var api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.VaquerosCore=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){"use strict";
var LABELS=Object.freeze({trabajo:{dobladillo:"Hacer un dobladillo",unir:"Unir piezas",pespunte:"Hacer un pespunte visible",reparar:"Reparar una zona"},grosor:{ligero:"Ligero",medio:"Medio",grueso:"Grueso",desconocido:"No lo sé"},capas:{pocas:"1–2 capas",varias:"3–4 capas",muchas:"Muchas capas"},cruce:{no:"No",si:"Sí"},maquina:{domestica:"Doméstica convencional",reforzada:"Heavy Duty / reforzada",desconocida:"No lo sé"}});
function item(id,title,text){return{id:id,title:title,text:text};}
function configure(input){var thick=input.grosor==="grueso",unknown=input.grosor==="desconocido",many=input.capas==="muchas",cross=input.cruce==="si",visible=input.trabajo==="pespunte",demanding=thick||many||cross;
var needle;if(input.grosor==="ligero"&&!many&&!cross)needle="Aguja Jeans/Denim, favoreciendo el extremo más fino apropiado para una máquina doméstica y este conjunto.";else if(thick)needle="Aguja Jeans/Denim 100/16 como referencia robusta de partida. El grosor acumulado puede requerir una superior si el manual y la máquina lo permiten.";else needle="Aguja Jeans/Denim aproximadamente 90/14–100/16 como rango orientativo para este conjunto.";
if(unknown)needle+=" Al no conocer el grosor, partimos de una opción intermedia y conviene comprobarla en un retal.";if(many||cross)needle+=" Comprueba que sea suficientemente robusta para atravesar todas las capas con normalidad.";
var thread=visible?"Hilo específico o de mayor presencia para pespunte en la parte superior si buscas ese acabado. Puede mantenerse hilo multiuso adecuado en la bobina si tu máquina lo admite. Prueba antes en un retal.":"Hilo resistente adecuado para costura de vaquero. Comprueba el resultado primero en un retal del mismo tejido.";
var stitch="Puntada recta como configuración de partida.";
var length=(visible||thick||input.grosor==="medio")?"Entre 3–4 mm como punto de partida orientativo, cuando la máquina y el acabado buscado lo permitan. Pruébalo en un retal.":"Longitud moderada, algo mayor que para un tejido muy fino, como punto de partida. Ajusta tras probar en un retal.";
var foot="Prensatelas universal/estándar mientras el arrastre sea regular.";if(many)foot="Mejora el arrastre si las capas no avanzan con regularidad; utiliza un prensatelas o accesorio apropiado solo si tu máquina dispone de él.";if(cross)foot="Mantén nivelado el prensatelas al pasar el desnivel. Puedes usar una placa niveladora apropiada o un retal doblado detrás cuando proceda.";
var technique=demanding?"Velocidad baja y controlada. Avanza sin forzar la máquina y detente si la aguja no atraviesa el conjunto con normalidad.":"Velocidad controlada/normal según tu máquina y el tejido, sin forzar el avance.";
var tension="Empieza con el ajuste normal recomendado por el fabricante y prueba en un retal del mismo tejido y con un número de capas parecido. Si la costura no queda equilibrada, consulta el manual de tu máquina.";
var parts=[item("aguja","🪡 Aguja",needle),item("hilo","🧵 Hilo",thread),item("puntada","〰️ Puntada",stitch),item("longitud","📏 Longitud de puntada",length),item("prensatelas","🦶 Prensatelas / arrastre",foot),item("tecnica","🐢 Velocidad / técnica",technique),item("tension","⚙️ Tensión",tension)];
var warnings=[];if(input.maquina==="domestica"&&demanding)warnings.push("Algunas máquinas domésticas pueden tener dificultades con este grosor. No fuerces la máquina si la aguja no atraviesa el conjunto con normalidad.");else if(input.maquina==="desconocida"&&demanding)warnings.push("Comprueba en el manual si tu máquina admite este conjunto y no la fuerces si la aguja no lo atraviesa con normalidad.");
var why=[];why.push(unknown?"Como no conoces el grosor, la aguja parte de una configuración intermedia y prudente.":"El grosor del denim y las capas determinan principalmente la robustez de la aguja y la velocidad.");if(cross)why.push("El cruce grueso exige controlar la velocidad y nivelar el prensatelas, sin cambiar lo que no depende del desnivel.");if(visible)why.push("El pespunte visible modifica sobre todo el hilo y la longitud para conseguir el acabado buscado.");if(input.maquina==="domestica"&&demanding)why.push("La combinación puede acercarse al límite de algunas máquinas domésticas, por eso conviene probar sin forzar.");
return{parts:parts,warnings:warnings,why:why,input:Object.assign({},input)};}
function compare(previous,next){var oldResult=configure(previous),newResult=configure(next),oldMap={},newMap={};oldResult.parts.forEach(function(x){oldMap[x.id]=x;});newResult.parts.forEach(function(x){newMap[x.id]=x;});var ids=Object.keys(newMap),oldWarnings=oldResult.warnings.join(" "),newWarnings=newResult.warnings.join(" ");var changed=ids.filter(function(id){return oldMap[id].text!==newMap[id].text;}).map(function(id){return newMap[id];});if(oldWarnings!==newWarnings)changed.push(item("aviso","Aviso sobre la máquina",newWarnings||"El aviso específico por grosor deja de ser necesario en esta configuración."));return{changed:changed,maintained:ids.filter(function(id){return oldMap[id].text===newMap[id].text;}).map(function(id){return newMap[id];}),result:newResult};}
return{configure:configure,compare:compare,labels:LABELS};});
